### ISSUE TITLE
How to send binary file in on_http() ?

### ISSUE THREAD

**Issue by PolarAir** [zaphoyd/websocketpp#1002]
`
void QuoteServer::on_http(websocketpp::connection_hdl hdl)
{
    auto path = connection->get_resource();
    if (path.find("/dbf") != std::string::npos)
    {
        // here I need to generate a dbf file and send it to http client
        // It's a binary file, and let's say we have the content and length
        char* buffer = gen_dbf();
        int len = get_dbf_len();
        auto connection = server_.get_con_from_hdl(hdl);
        // my question is how to send this out? set_body only accept std::string
        connection->set_body(buffer); // ???

        connection->replace_header("Content-Type", "application/octet-stream");
        connection->replace_header("Content-Length", std::to_string(len));
        connection->replace_header("Content-Disposition", "attachment");
        connection->replace_header("Content-filename", "cache_" + exchange + ".dbf");
        connection->set_status(websocketpp::http::status_code::ok);
    }
}
`

**Comment by zaphoyd** [comment]
There are no limits to what byes you can put in a `std::string`, so you should be able to load a binary file into one and send it has the payload with `set_body`.

**Comment by PolarAir** [comment]
> There are no limits to what bytes you can put in a `std::string`, so you should be able to load a binary file into one and send it as the payload with `set_body`.

oh thx. I tried it out and it works! I'll close this thread.
Thx again!
