### ISSUE TITLE
#include <websocketpp/client.hpp>  v.  #include "websocketpp/client.hpp"

### ISSUE THREAD

**Issue by pha377** [zaphoyd/websocketpp#1003]
Hi all,

When building my project,
it doesn't recognize `#include <websocketpp/client.hpp>`
but it does with `#include "websocketpp/client.hpp"`

Also with `#include <websocketpp/client.hpp>` the IDE (Kdevelop) doesn't recognize it, so it shows me hundreds of errors.

I managed to solve it once but, I don't remember how =(

I have downloaded websocketpp in root of my project
So it is in /project/websocketpp/

An example of CMakeLists.txt file would be nice

There is a file /websocketpp/CMakeLists.txt with:
```
init_target("websocketpp")
final_target ()
```
When building it doesn't like `init_target("websocketpp")`

**Comment by pha377** [comment]
I've tried with this makefile, but it complains about `Unknown CMake command "init_target"`

```
cmake_minimum_required(VERSION 3.0)
project(myproj)
add_subdirectory(websocketpp)
add_executable(myproj monitor.cpp) 
target_compile_features(myproj PUBLIC cxx_std_20)
target_compile_options(myproj PRIVATE -Wall -Wextra -pedantic -Werror)
target_link_libraries(myproj PRIVATE pthread crypto ssl)


```

**Comment by zaphoyd** [comment]
The difference between quotes and angle brackets for includes in the C preprocess or is described in section 6.10.2 of the standard (http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf#page=182). In short it is entirely up to the specific compiler in use to define the meaning. It usually has to do with where the compiler looks for files to include.

WebSocket++ has no preference, you’ll need to follow the rules for your compiler/IDE.

**Comment by zaphoyd** [comment]
`init_target` is a cmake macro defined in https://github.com/zaphoyd/websocketpp/blob/master/cmake/CMakeHelpers.cmake, you can look at that file for details about what it is doing with respect to specifying include directories.
