### ISSUE TITLE
Disabling console output

### ISSUE THREAD

**Issue by 0xDani3l** [zaphoyd/websocketpp#1011]
Hi, is there a method I can use to disable console logging of my server completely? Here is my server code

https://pastebin.com/raw/H4JtJjz6

Thanks

**Comment by aran1177** [comment]
c.set_access_channels(websocketpp::log::alevel::all);
        c.clear_access_channels(websocketpp::log::alevel::frame_payload);
        c.set_error_channels(websocketpp::log::elevel::all);

examples/print_client/print_client.cpp

**Comment by demonlol** [comment]
This is what I did below. It's in the documentation.

clientele.set_access_channels(websocketpp::log::alevel::none);
clientele.set_error_channels(websocketpp::log::elevel::none);

**Comment by sweihub** [comment]
> This is what I did below. It's in the documentation.
> 
> clientele.set_access_channels(websocketpp::log::alevel::none); 
> clientele.set_error_channels(websocketpp::log::elevel::none);

Thanks, this completely turns off the logging.
