### ISSUE TITLE
Discrepency in documetnation/example/implementation with get_con_from_hdl() and endpoint::close()

### ISSUE THREAD

**Issue by joesdiner** [zaphoyd/websocketpp#1071]
In the [utility client example](https://docs.websocketpp.org/md_tutorials_utility_client_utility_client.html) the documentation states:

> Handles may be upgraded to a `connection_ptr` during a handler call by using `endpoint::get_con_from_hdl()`. The resulting `connection_ptr` is safe to use for the duration of that handler invocation.

Along with the text in the "When is it safe to use connection_ptr?" section saying that `connection_ptr`'s should only be used in a handler, I'm taking this to mean that `endpoint::get_con_from_hdl()` should ever be called in a handler. Please correct me if this is wrong, as it makes the rest of this post moot.

However, the implementation for `websocketpp::endpoint::close()` is:

````
template <typename connection, typename config>
void endpoint<connection,config>::close(connection_hdl hdl, close::status::value
    const code, std::string const & reason,
    lib::error_code & ec)
{
    connection_ptr con = get_con_from_hdl(hdl,ec);
    if (ec) {return;}
    con->close(code,reason,ec);
}
````

This uses `get_con_from_hdl()`, even though the documentation in the tutorial says "`endpoint::close`. This is a thread safe method that is used to asynchronously dispatch a close signal to the connection with the given handle", which seems to mean it can be called from any thread, which seems to contradict the statements about `get_con_from_hdl()`

Further along in the utility client example under "Add close method to websocket_endpoint" it adds the following function:

````
void close(int id, websocketpp::close::status::value code) {
    websocketpp::lib::error_code ec;
    
    con_list::iterator metadata_it = m_connection_list.find(id);
    if (metadata_it == m_connection_list.end()) {
        std::cout << "> No connection found with id " << id << std::endl;
        return;
    }
    
    m_endpoint.close(metadata_it->second->get_hdl(), code, "", ec);
    if (ec) {
        std::cout << "> Error initiating close: " << ec.message() << std::endl;
    }
}
````

This uses `endpoint::close()` which calls `get_con_from_hdl()`, but the above `close()` function isn't called from a handler, but the main user interaction thread. This means that in the tutorial example `get_con_from_hdl()` is being (indirectly) called from a thread that isn't a handler.

All this indicates to me that there is a disconnect between the documentation, tutorial example, and/or the implementation. Please correct my understanding if I misinterpreted something and indeed the previously mentioned resources are in concert. Or else any advice on what the actual source of truth is for using `endpoint::close` and/or `get_con_from_hdl()` would be appreciated.

**Comment by zaphoyd** [comment]
Good question. As you've identified the real answer here is a bit more complicated than the documentation suggests. Specifically the WebSocket++ API is divided into two sections, one API that works with `Endpoint` objects that is synchronized by locks and refers to connections via the `connection_hdl` (a weak pointer). Opposite this is another API that works with `Connection` objects and is synchronized by the transport layer's guarantee that handlers for a given connection are never executed concurrently.

All `Connection` methods are safe to use inside handlers. Some `Connection` methods have additional locking that allows them to be safely used outside of a handler. Such methods, such as `close`, are wrapped by the `Endpoint` API that accepts a hdl, does the upgrade and forwarding to connection for you.

When the documentation says `connection_ptr`/`get_con_from_hdl` should only be used inside handlers it means that if you stick to this rule of thumb you won't end up in trouble from a threading perspective, not that literally there are no safe uses of a `connection_ptr` outside of a handler.

When the library is used idiomatically, `get_con_from_hdl` and the resulting `connection_ptr` never need to be used outside of a handler. Every action on a `Connection` that is safe to be called from anywhere is wrapped in an `Endpoint` method that accepts a `connection_hdl`.

**Comment by joesdiner** [comment]
Thanks for the quick response and clarification. I'm not using `get_con_from_hdl()` outside a handler so I should be fine. I just wanted to make sure there wasn't a problem in the implementation, which there isn't. I'm going to go ahead and close this issue.
