### ISSUE TITLE
The event message sent from the server is lost.

### ISSUE THREAD

**Issue by ChanryX** [zaphoyd/websocketpp#1152]
I should receive four event messages from the server on the client, but I only received three. I have printed relevant logs in the `void connection<config>::handle_read_frame(lib::error_code const & ec,size_t bytes_transferred) `function, but I cannot find deeper problems. I would like to ask how to get the bottom-level data frame and some error troubleshooting methods. Thank you.

**Comment by Jacob-Burckhardt** [comment]
How many messages does Wireshark show?

**Comment by ChanryX** [comment]
> How many messages does Wireshark show?
After investigation, the issue was found to be in the business logic layer. The problem has been resolved now. Thank you for your suggestion.

**Comment by ChanryX** [comment]
@Jacob-Burckhardt After investigation, the issue was found to be in the business logic layer. The problem has been resolved now. Thank you for your suggestion.
