### ISSUE TITLE
How to handle CTRL+C gracefully?

### ISSUE THREAD

**Issue by snowuyl** [zaphoyd/websocketpp#1154]
I added  gWsServer.stop_listening() and gWsServer.stop() when user click CTRL+C button. But unfortunatelly when I run websocket_server again. The following error messages occurred. How to handle CTRL+C gracefully?
./websocket_server 
[2024-12-11 13:22:55] [info] asio listen error: system:98 (Address already in use)
Underlying Transport Error

typedef websocketpp::server<websocketpp::config::asio> server;
typedef server::message_ptr message_ptr;
server  gWsServer;
void handleSigint(int sig) {
    gWsServer.stop_listening();
    gWsServer.stop();
}

void onMessage(server* s, websocketpp::connection_hdl hdl, server::message_ptr msg) {
}

int main() {
    try {
        signal(SIGINT, handleSigint);
        gWsServer.set_access_channels(websocketpp::log::alevel::all);
        gWsServer.clear_access_channels(websocketpp::log::alevel::frame_payload);
        gWsServer.init_asio();
        gWsServer.set_message_handler(std::bind(&onMessage, &gWsServer, std::placeholders::_1, std::placeholders::_2));
        gWsServer.listen(9002);
        gWsServer.start_accept();
        gWsServer.run();
    } catch (websocketpp::exception const & e) {
        std::cout << e.what() << std::endl;
    } catch (...) {
        std::cout << "other exception" << std::endl;
    }

    return 0;
}

**Comment by snowuyl** [comment]
Thanks for your reply! I have changed signal handler as follows. But this issue still occurred.
void handleSigint(int sig) {
    gWsServer.stop_listening();
    gWsServer.stop();
    gWsServer.set_reuse_addr(true);
}

**Comment by Jacob-Burckhardt** [comment]
Try moving your set_reuse_addr call to right after the init_asio call.

**Comment by snowuyl** [comment]
Thanks for your great support! This issue has been fixed after moving set_reuse_addr call to right after the init_asio call.
