### ISSUE TITLE
Safari 5.1.7 doesn't connect via wss

### ISSUE THREAD

**Issue by ghost** [zaphoyd/websocketpp#126]
First, big thanks for a great library!

Works like a charm, except with Safari 5.1.7 (and possibly others) on Macosx when using secure mode. The debug log gives this error:
```
Socket initialization failed, error code: asio.ssl:336130315
```
which translates to 
```
SSL routines:SSL3_GET_RECORD:wrong version number 
```

I assume it might not really be an issue with webscoketpp, but rather with asio ssl, but given that Safari has no problem retrieving regular https contents but does choke on websockets, I don't even know where to start looking for the root cause. 

Maybe someone has any ideas?

**Comment by zaphoyd** [comment]
Closing this issue as it was a problem with a now obsolete version of Safari with a now obsolete version of TLS. Modern versions of Safari & TLS work.
