### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by jefferai** [zaphoyd/websocketpp#132]
Hi,

Thanks for the library...it looks super useful.

That said, one of the reasons I'm interested in WebSockets as a transport mechanism is the possibility of using it over an http proxy. I've tested this in-browser and it works via the proxy in question, but I can't figure out how I'd do it with websocketpp. I've looked around at boost::asio documentation and don't really see anything in there, either, except for one person that did it with a lot of very specific manual code, which I'm not sure it'd be easy to shoehorn into websocketpp (http://lists.boost.org/boost-users/2008/05/36356.php).

Any advice?

Thanks,
Jeff

**Comment by grasmanek94** [comment]
What about SOCKS4/5 proxies? Are they supported? I can't find any documentation about proxying.
