### ISSUE TITLE
Windows Visual Studio 2010 Solution / Project Errors  & Warnings.

### ISSUE THREAD

**Issue by rsaccone** [zaphoyd/websocketpp#147]
Hello,

In trying to build the Windows version, I noticed that there are several files included in the Visual Studio project that don't actually exist.  

For example, the websocketpp project has:
websocket_client.hpp
websocket_client_session.hpp
websocket_connection_handler.hpp
websocket_server.hpp
websocket_server_session.hpp
websocket_session.hpp

Are these still required, and if so, where might they be found?

There is an error in building the wsperf project.  Precompiled headers are enabled for the project but an error is reported because wperf.cpp doesn't include StdAfx.h.  StdAfx.h is missing from the project.

Additionally, there are many warnings generated regarding due to checked iterators defaulting to on.   Is it safe to disable them?

Thanks in advance,
Robert.

**Comment by zaphoyd** [comment]
I believe most of the Visual Studio related warnings (other than the checked iterator ones that I won't fix) have been fixed now. If anyone finds new serious warnings when building with Visual Studio please open a new issue.
