### ISSUE TITLE
API for binary stream not documented

### ISSUE THREAD

**Issue by breyed** [zaphoyd/websocketpp#167]
In the latest code on master, there is only one overload of `handler_interface::on_message`. The [documentation][1] speaks of separate overloads for text and binary. However, it appears from the current code that `on_message` only supports text and always does UTF-8 checking. The documentation should be updated to show how to use it.

  [1]: https://github.com/zaphoyd/websocketpp/wiki/Connection-Handler-API

**Comment by zaphoyd** [comment]
Not going to be writing any more docs for obsolete/experimental 0.2.x versions.
