### ISSUE TITLE
Endpoint timer should use steady clock

### ISSUE THREAD

**Issue by breyed** [zaphoyd/websocketpp#241]
`endpoint::set_timer` creates a new `boost::asio::deadline_timer`. The actual duration that this timer waits changes if the system clock changes. Typically, timeouts related to networking should be independent of changes to the system clock. To achieve independence, use `steady_timer` instead. See the [Boost Clocks documentation](http://www.boost.org/doc/libs/1_53_0/doc/html/chrono/users_guide.html#chrono.users_guide.tutorial.clocks) for background.

**Comment by zaphoyd** [comment]
This issue has been addressed on the develop branch and the fix will be included in 0.6.0

**Comment by zaphoyd** [comment]
The 0.6.0 release included this fix.
