### ISSUE TITLE
TLS short read when closing connection

### ISSUE THREAD

**Issue by breyed** [zaphoyd/websocketpp#263]
WebSocket++ reports an error when it acts as a client and connects to a [AspNetWebSocket](http://msdn.microsoft.com/en-us/library/hh160736.aspx) with TLS.

This is the sequence:
1. WebSocket++ connects to AspNetWebSocket.
2. WebSocket++ initiates normal closure.
3. AspNetWebSocket calls CloseAsync (which sends a normal closure acknowledgement).
4. WebSocket++ reports the following messages:

> [2013-06-09 19:59:43] [control] Control frame received with opcode 8
> [2013-06-09 19:59:43] [error] got TLS short read, killing connection for now
> [2013-06-09 19:59:43] [info] asio async_shutdown error: asio.ssl:335544539 (short read)
> [2013-06-09 19:59:43] [error] Underlying Transport Error

5. WebSocket++ calls the close handler.
6. WebSocket++ reports the following message:

> [2013-06-09 20:02:27] [disconnect] Disconnect close local:[1006,TLS Short Read] remote:[1000]
> [2013-06-09 20:09:03] [info] asio async_read_at_least error: asio.ssl:336130329 (decryption failed or bad record mac)
> [2013-06-09 20:09:03] [fatal] error in handle_read_frame: Underlying Transport Error (websocketpp.transport:2)

The last two messages only occurred when I sat at a breakpoint for a long time (a couple minutes?) immediately before CloseAsync was called.

Despite the messages, everything seems to work correctly and the fail handler does not get called.

**Comment by TechnikEmpire** [comment]
Can you reference the diff or just the sources where you applied changes to resolve this problem? Unfortunately the interwebs seems lacking on results for this issue, in fact your thread here comes up #1 result if I use "boost" along with the ec.
