### ISSUE TITLE
access violation on disconnect

### ISSUE THREAD

**Issue by otaras** [zaphoyd/websocketpp#293]
When tsl connection is used there could be a case when connection is destructed already while read operation is not finished yet.

The root cause looks to be in websocketpp\transport\asio\connection.hpp file where void async_read_at_least method uses plain this pointer to bind handle_async_read operation. There are a lot of such binds that looks potentially dangerous.

**Comment by zaphoyd** [comment]
Releases between this point, through 0.7 have greatly improved the safety of Asio's thread pool mode. Going to close this now. If there are new specific problems with Asio thread pool mode, please open as new issues.

**Comment by n-mam** [comment]
Very recently we faced the exact same crash. Although the circumstances might not be the same here but just wanted to highlight that the problem for us was with the ordering of one of the class member of type boost::asio::ip::tcp::socket before the member of type boost::asio::io_service. 

With this setup the dtor of the socket gets called before the dtor for io_service. The critical section which the above code faults on, gets default destructed deep inside the dtor for the boost::asio::ip::tcp::socket  member. 

Moving boost::asio::io_service member before the boost::asio::ip::tcp::socket member fixed this crash.

Neelabh
