### ISSUE TITLE
Support permessage-deflate extension

### ISSUE THREAD

**Issue by zaphoyd** [zaphoyd/websocketpp#344]
https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-17

There is an experimental branch of WebSocket++ already with support for a (very slightly) older version of this spec already. As the spec has had no further changes in the last few months it is time to clean that branch up and get it ready for production use.

**Comment by zaphoyd** [comment]
basic permessage-deflate support was available in 0.6.0-permessagedeflate as well as the 0.7.0 release

**Comment by Aaronov** [comment]
How does one make use of this extension? Is it just a matter of including "websocketpp/extensions/permessage_deflate/enabled.hpp"?

**Comment by zaphoyd** [comment]
permessage-deflate support is added via the config template parameter sent to your endpoints. I don't yet have convenience configs (like the ones for asio/tls) that have this extension included yet so you will need to make a custom config. The convenience configs will hopefully by done for 0.8.

There is an FAQ item at http://doxygen.websocketpp.org/faq.html (Compression section) that describes how to make a custom config that includes permessage-deflate support.
