### ISSUE TITLE
websocketpp boost dependency

### ISSUE THREAD

**Issue by se21** [zaphoyd/websocketpp#353]
I have been using websocketpp 0.2x, then upgraded to the version websocketpp 0.3xexperimental. But I guess, still the library is dependent on boost::asio.
Is there any version of websocketpp which doesn't uses boost or any alternative to get rid of boost???

Also I read something like this
"WebSocket++ implements a pluggable data transport component. The default component allows reduced functionality by using STL iostream. This component has no non-STL dependencies and can be used in a C++11 environment without Boost. Also included is a Boost ASIO based transport component that provides full featured network client/server functionality. This component requires Boost ASIO. "

Following this, I tried to create a basic app by just including server.hpp. I'm getting the following error.

"fatal error C1083: Cannot open include file: 'boost/system/error_code.hpp': No such file or directory"

Please guide me to use the default websocket component(w/o boost).

Thanks in advance

**Comment by zaphoyd** [comment]
So an update on this. There are now two ways to use WebSocket++ without boost. One is to use the iostream transport (which allows you to supply your own networking logic). The other is to use the standalone (non-boost) version of Asio along with a C++11 standard library. The latter is fairly well described in official documentation. The former is not. I am going to close this support issue and open another issue specifically for the iostream transport docs.
