### ISSUE TITLE
Connections time out under heavy loads

### ISSUE THREAD

**Issue by robinrowe** [zaphoyd/websocketpp#361]
My websocketpp client opens connections as fast as it can, a load test. After about 30s the server responds by refusing connections. 

The error message is "error in handle_read_handshake: End of File". It's an on_fail "Time Expired" with state = 9. That's invalid_state, right? Why?

I have set_open_handshake_timeout(0). I don't see any other timers to disable for connecting. What's timing out? How do I stop the server from timing out connections?

My clients send a connect string once connected. Should I make the server talk first so I won't have thousands of fresh connects all talking at once?

Ideas?

Robin

**Comment by zaphoyd** [comment]
I believe that the fix for this issue is now present in the 0.5.0 release on the master branch. If anyone has additional similar issues please reopen.
