### ISSUE TITLE
building tests using CMake 

### ISSUE THREAD

**Issue by dnovikoff** [zaphoyd/websocketpp#378]
I was trying to build all examples and tests with cmake. Still it looks like tests contains no cmake file. Am I missing something, or I cant build tests from cmake with the current cmake files state?

**Comment by zaphoyd** [comment]
This is going to be the official issue for getting the CMake build system for test/examples up to parity with the scons system.

**Comment by zaphoyd** [comment]
This is now fixed on the develop branch. CMake should build all tests and examples.
