### ISSUE TITLE
websocket++ Client/Server on the Windows XP

### ISSUE THREAD

**Issue by heylogt** [zaphoyd/websocketpp#385]
I use the examples named "echo_client" and "echo_server".The Server and Client can run normally on the Win7 and win8.It prompts "invalid state" when the programs run on the winXP.The Client can't connect with the Server.

**Comment by Gjacquenot** [comment]
I encountered the same problem on Windows XP
I solved the problem by changing

    server.listen(9002);

with

    server.listen("127.0.0.1","9002");

**Comment by bdwade100** [comment]
I encountered the same problem on Windows XP. My solution was similar to Gjacquenot's.

I solved it by changing

`server.listen(9002);`

to

`server.listen(boost::asio::ip::tcp::v4(), 9002);`
