### ISSUE TITLE
Potential buffer overrun reported by coverity 

### ISSUE THREAD

**Issue by grover** [zaphoyd/websocketpp#387]
As I unfortunately can not push to this repository, here's the diff to the current master and a description of the issue reported by a coverity scan of the source tree. There are other less critical error reports that I'd like to fix over time, but this is the most severe.

The coverity report in short:

connection_impl.hpp:769 - cond_at_most: Checking bytes_processed > 16384UL implies that bytes_processed has the value which may be up to 16384 on the false branch

connection_impl.hpp:817 - overrun-local: Overrunning array of 16384 bytes at byte offset 16384 by dereferencing pointer &this->m_buf[bytes_processed]

Additionally the same issue can appear the check on line 751 in connection_impl.hpp. The fix for both of the issues is included in the following unified diff:

--- a/websocketpp/impl/connection_impl.hpp
+++ b/websocketpp/impl/connection_impl.hpp
@@ -747,8 +747,8 @@ void connection<config>::handle_read_handshake(lib::error_code const & ec,
         return;
     }
 
-    // Boundaries checking.
-    if (bytes_transferred >= config::connection_read_buffer_size) {
+    // Boundaries checking. TODO: How much of this should be done?
+    if (bytes_transferred > config::connection_read_buffer_size) {
         m_elog.write(log::elevel::fatal,"Fatal boundaries checking error.");
         this->terminate(make_error_code(error::general));
         return;
@@ -766,7 +766,8 @@ void connection<config>::handle_read_handshake(lib::error_code const & ec,
     }
 
     // More paranoid boundaries checking.
-    if (bytes_processed >= config::connection_read_buffer_size) {
+    // TODO: Is this overkill?
+    if (bytes_processed > config::connection_read_buffer_size) {
         m_elog.write(log::elevel::fatal,"Fatal boundaries checking error.");
         this->terminate(make_error_code(error::general));
         return;

I hope this helps.

Thanks!
Michael

**Comment by zaphoyd** [comment]
Closing this as I believe the logic is resulting in a false positive from the static analyzer. Please re-open if there is any more evidence that this is not the case.
