### ISSUE TITLE
Compiling simple_broadcast_server

### ISSUE THREAD

**Issue by samuelcolvin** [zaphoyd/websocketpp#394]
I'm having trouble compiling the `simple_broadcast_server.cpp` example. I'm running

    g++ simple_broadcast_server.cpp  -I ~/websocketpp/ -lboost_system

and getting a multitude of errors. I assuming I'm doing something dumb wrong?

(I can give dump of errors, but I assume my problem is something obvious in the compile command).

**Comment by samuelcolvin** [comment]
i tried that and got lots more errors, I guess there's something else I need to Install? I'll have another go tomorrow.

(I'm on Ubuntu 14.04).

**Comment by zaphoyd** [comment]
I pulled up a 14.04 VM, installed boost from the regular ubuntu package and websocketpp from github. I think I see one other potential thing for you to try. If you are using the master branch (v0.4.0) you will also need the following flag `-D_WEBSOCKETPP_CPP11_STL_` in conjunction with `-std=c++11`. If you are using the develop branch / upcoming 0.5.0 release that build flag is no longer required.

**Comment by zaphoyd** [comment]
I believe this has been resolved, if not, please re-open.
