### ISSUE TITLE
Cmake dosn't build all the examples in windows 

### ISSUE THREAD

**Issue by meiry** [zaphoyd/websocketpp#396]
Using VC 2013 the community version windows 7 32 bit 
when running cmake via cmake GUI , checking the BUILD_TESTS and BUILD_EXAMPLES and 
the testes gives error:
```
CMake Warning (dev) at CMakeLists.txt:229 (add_subdirectory):
  The source directory

    D:/dev/cpp/websocket_server/git/websocketpp/test

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.


and the examples that do build are :
debug_server
echo_server
echo_server_both
echo_server_tls
print_server
sip_client
telemetry_client
testee_client
utility_client

other missing 

here is my cmake output
```
* Configuring Boost
-- Using BOOST_ROOT
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0
-- Include Directories
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0
-- Library Directories
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib
-- Libraries
       optimized
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_system-vc120-mt-1_55.lib
       debug
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_system-vc120-mt-gd-1_55.lib
       optimized
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_thread-vc120-mt-1_55.lib
       debug
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_thread-vc120-mt-gd-1_55.lib
       optimized
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_random-vc120-mt-1_55.lib
       debug
       d:/dev/cpp/libs/boost_1_55_0/boost_1_55_0/stage/lib/libboost_random-vc120-mt-gd-1_55.lib

Found OpenSSL: d:/dev/cpp/libs/openssl-1.0.1e-win32-bin/openssl/lib/ssleay32.lib;d:/dev/cpp/libs/openssl-1.0.1e-win32-bin/openssl/lib/libeay32.lib (found version "1.0.1e") 
** websocketpp
** debug_server
-- Build Type:
       EXECUTABLE
** echo_server
-- Build Type:
       EXECUTABLE
** echo_server_both
-- Build Type:
       EXECUTABLE
** echo_server_tls
-- Build Type:
       EXECUTABLE
** print_server
-- Build Type:
       EXECUTABLE
** sip_client
-- Build Type:
       EXECUTABLE
** telemetry_client
-- Build Type:
       EXECUTABLE
** testee_client
-- Build Type:
       EXECUTABLE
** utility_client
-- Build Type:
       EXECUTABLE
CMake Warning (dev) at CMakeLists.txt:229 (add_subdirectory):
  The source directory

    D:/dev/cpp/websocket_server/git/websocketpp/test

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

=========== Used Build Configuration =============

ENABLE_CPP11        = ON
BUILD_EXAMPLES      = ON
BUILD_TESTS         = ON

WEBSOCKETPP_ROOT    = D:/dev/cpp/websocket_server/git/websocketpp
WEBSOCKETPP_BIN     = D:/dev/cpp/websocket_server/git/websocketpp/build/bin
WEBSOCKETPP_LIB     = D:/dev/cpp/websocket_server/git/websocketpp/build/lib
Install prefix      = D:/dev/cpp/websocket_server/git/websocketpp/install

WEBSOCKETPP_BOOST_LIBS        = system;thread;random
WEBSOCKETPP_PLATFORM_LIBS     = 
WEBSOCKETPP_PLATFORM_TSL_LIBS = 

Configuring done
Generating done

do i do something wrong ? 
what is the proper way to run the cmake in windows ?

**Comment by meiry** [comment]
ok after digging in the Cmake files i see there are missing CMakeLists.txt files in the missing examples dires , is there שמט reason for that ?

**Comment by zaphoyd** [comment]
There is no reason for the cmake example/test build system to be incomplete other than nobody has finished it yet.

**Comment by zaphoyd** [comment]
Going to close this and track future progress on this issue in the existing #378 issue
