### ISSUE TITLE
m_server.stop_listening() does not cause run() to exit

### ISSUE THREAD

**Issue by markus-bonk** [zaphoyd/websocketpp#399]
I have a websocketpp::server<websocketpp::config::asio_tls> server which is listening with no other active connections.

a stop routine executes

  websocketpp::lib::error_code ec;
  if (m_server.is_listening())
    m_server.stop_listening(ec);

I would expect the run() method to exit. However it does not even though the connection instance is destructed. Do I need to do anything else to get the run() to exit?

**Comment by zaphoyd** [comment]
I would also expect run to exit when there are no connections left and the server is told to stop listening. Some things to look for: do you have any timers set? do you use the underlying io_service for anything else?

**Comment by markus-bonk** [comment]
Thank you for the hint: I was using the io_service in boost::asio::signal_set to wait on some signals. Canceling the async_wait resolved this issue for me. Thanks you.
