### ISSUE TITLE
Potentially uninitialized local variable used

### ISSUE THREAD

**Issue by halex2005** [zaphoyd/websocketpp#402]
Hi!
Thanks for great library!
I just start to use it.
I compile my project with MSVC2013 and websocketpp v0.5.0 from master branch.

MSVC2013 gives warning:
d:\development\git\ewcc-pjsip\third-party\websocketpp\websocketpp\processors\hybi13.hpp(575): warning C4701: potentially uninitialized local variable 'key' used

I looked at the code and it turns out that MSVC2013 was right. But I cannot understand how to fix this warning for now. Any thoughts? Is this key variable critical in this place?

Best regards, Aleksei.

**Comment by zaphoyd** [comment]
The code is correct, the variable is required. In all cases where key is used it is initialized. In the cases where it is unused it is uninitialized. I've added an explicit initialization to null that should suppress this warning. Can you confirm that the develop branch no longer produces this warning on your compiler?

**Comment by halex2005** [comment]
Sorry for late answer. I tryed to compile develop branch and yes, this warning is gone. Thank you!
