### ISSUE TITLE
test/http/parser.cpp line 712 maybe wrong?

### ISSUE THREAD

**Issue by Huangdong2** [zaphoyd/websocketpp#404]
on
https://github.com/zaphoyd/websocketpp/blob/master/test/http/parser.cpp
line: 712
                                            wrong?-----
                                                              |
                                                              |
there's a line:        std::string raw = "GE]T / HTTP/1.1\r\nHost: www.example.com\r\n\r\n";
should it be:          std::string raw = "GET / HTTP/1.1\r\nHost: www.example.com\r\n\r\n";
?

**Comment by zaphoyd** [comment]
This is intended and correct. Specifically, the misspelling is part of a unit test that tests whether or not the parser correctly rejects invalid HTTP methods.
