### ISSUE TITLE
Client does not handle binary payloads due to std::string type and null termination

### ISSUE THREAD

**Issue by aweigold** [zaphoyd/websocketpp#412]
When using get_payload, or get_raw_payload, a std::string is returned, however when receiving a binary payload, null characters terminate the string.

Would it be possible to add support for get_payload_bytes and get_raw_payload_bytes?

(I am working on trying a fix and will submit a pull request if I can do it, but my c++ is not as good as my Java.)

**Comment by zaphoyd** [comment]
std::string is not null terminated and can be used for binary data. The data() method can be used to retrieve a pointer to the data buffer and the size() method is used to retrieve the length of the buffer. The buffer returned by data() may contain null bytes as well as any other bytes.

**Comment by aweigold** [comment]
Thanks, got confused with c strings... this is working.
