### ISSUE TITLE
how to get client's ip and port?

### ISSUE THREAD

**Issue by q191201771** [zaphoyd/websocketpp#422]
as a server,how to get client's ip and port?
is there any convenient interface in connection_hdl or anywhere?

**Comment by zaphoyd** [comment]
`connection::get_remote_endpoint()` will return a human readable address+port as a string for the connected client (in the case of a server) or the connected server (in the case of a client). This should work independently of the transport policy in use (though some transport policies may provide more or less information than others)

An alternative, that works only with the asio transport, you can query the remote endpoint directly. `connection::get_raw_socket()` will return a `boost::asio::ip::tcp::socket &` which you can then query for all of the various machine or human readable details about the local and remote endpoint. See http://stackoverflow.com/questions/5352757/boost-asio-socket-how-to-get-ip-port-adress-of-connection and http://stackoverflow.com/questions/601763/how-to-get-ip-addresss-of-boostasioiptcpsocket for some details on extracting information from the asio socket.

**Comment by q191201771** [comment]
thx a lot
