### ISSUE TITLE
undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by hartsantler** [zaphoyd/websocketpp#426]
Server example compile ok.  I'm using Fedora21 64bits. heres the full error:
```bash
[brett@localhost bu]$ make
Scanning dependencies of target debug_server
[ 10%] Building CXX object examples/debug_server/CMakeFiles/debug_server.dir/debug_server.cpp.o
Linking CXX executable ../../bin/debug_server
[ 10%] Built target debug_server
Scanning dependencies of target utility_client
[ 20%] Building CXX object examples/utility_client/CMakeFiles/utility_client.dir/utility_client.cpp.o
Linking CXX executable ../../bin/utility_client
/bin/ld: CMakeFiles/utility_client.dir/utility_client.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/utility_client/CMakeFiles/utility_client.dir/build.make:88: recipe for target 'bin/utility_client' failed
make[2]: *** [bin/utility_client] Error 1
CMakeFiles/Makefile2:182: recipe for target 'examples/utility_client/CMakeFiles/utility_client.dir/all' failed
make[1]: *** [examples/utility_client/CMakeFiles/utility_client.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by KennyGeyskens** [comment]
I've had the exact same issue today trying to compile on rasbian using codeblocks.

**Comment by zaphoyd** [comment]
My first guess is that you aren't linking to libpthread? The bundled cmake/scons config for the examples will try and detect this, but if you are using an unusual compiler or OS it might not be detecting it correctly.

**Comment by kengey** [comment]
That seems tot be the issue. Now on tot the next one :) address family nog supporter by protocol. But maybe I should open a new issue for this one.

**Comment by zaphoyd** [comment]
address family not supported is likely that your platform doesn't have an IPv6 stack. By default WebSocket++'s Asio transport will listen on all interfaces for both the IPv4 and IPv6 address families. There are some overloads to endpoint::listen that let you explicitly specify which address, interface, or address family to listen on. You may have luck either enabling IPv6 on your platform (ideal) or disabling IPv6 in your WebSocket++ program.

**Comment by kengey** [comment]
Forgot to mention that this solved the issue.

**Comment by zaphoyd** [comment]
This issue appears to be solved.
