### ISSUE TITLE
Warning C4996: 'std::_Copy_impl': Function call with parameters that may be unsafe.

### ISSUE THREAD

**Issue by sheeeng** [zaphoyd/websocketpp#431]
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(2132): warning C4996: 'std::_Copy_impl': Function call with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
	1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(2113) : see declaration of 'std::_Copy_impl'
	1>          C:\Path\To\websocketpp-0.5.1\websocketpp/frame.hpp(255) : see reference to function template instantiation '_OutIt std::copy<uint8_t*,uint8_t*>(_InIt,_InIt,_OutIt)' being compiled
	1>          with
	1>          [
	1>              _OutIt=uint8_t *
	1>  ,            _InIt=uint8_t *
	1>          ]

Could this warning be fixed in future releases?

**Comment by zaphoyd** [comment]
This is a spurious warning from Visual Studio for something that is not a problem. There isn't a particularly reliable and safe way of disabling the warning unilaterally on the library's end. See http://stackoverflow.com/questions/1301277/c-boost-whats-the-cause-of-this-warning for a good explanation of what is happening here and how to disable this warning.
