### ISSUE TITLE
How to get Listen fd of server

### ISSUE THREAD

**Issue by krishna3189** [zaphoyd/websocketpp#436]
I am trying to integrate server with a foreign event loop . How to get the listen fd of the server so that the fd can be given to foreign event loop for monitoring . I am able to get the new connection fds but not the listen fd .

**Comment by zaphoyd** [comment]
The `tcp_pre_bind` handler allows access to the accepter after it is initialized and open but before it is bound and listening. You should be able to access the listen fd of the service through the acceptor's `native_handle()` method. I'm not entirely sure how useful this will be (probably not any less useful than the connection fds). For more information about foreign event loops take a look at the raw/iostream transport and support for external Asio `io_context` (including the bundled `iostream_server` and `external_io_service` examples)
