### ISSUE TITLE
Windows XP/ Windows Server 2003 , crash after requesting http data

### ISSUE THREAD

**Issue by thoys** [zaphoyd/websocketpp#460]
when using the websocketpp::server<websocketpp::config::asio_tls> http_handler . and a connection is made. This times out after a while. Which cause a cancel event being called on the socket. This is not supported in Windows XP and Windows Server 2003 even if compiled on a different OS.

My workaround is to define BOOST_ASIO_ENABLE_CANCELIO , see http://www.boost.org/doc/libs/1_35_0/doc/html/boost_asio/using.html for more info.

**Comment by zaphoyd** [comment]
I've pushed an update to `develop` that may resolve this issue by handling this error within the libraries logging framework rather than throwing an exception and dying.

**Comment by thoys** [comment]
Yep this fixed it! Thanks!
