### ISSUE TITLE
error with echo_server_tls

### ISSUE THREAD

**Issue by hs79hs** [zaphoyd/websocketpp#463]
Hello, I am using websocketpp-0.6.0 and have successfully run echo_server example. But when I try echo_server_tls, I have the following error:

on_tls_init called with hdl: 0x14e4370
using TLS mode: Mozilla Intermediate
[2015-09-02 07:38:58] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2015-09-02 07:38:58] [fail] WebSocket Connection [::ffff:60.207.193.194]:25585 - "" - 0 websocketpp.transport:8 TLS Short Read

My client is a HTML5 file with the code like this:
websocket = new WebSocket("wss://serverIP:9002");
And the browser is Chrome.

I just use server.pem and dh.pem provided with examples/echo_server_tls.
Have no idea about how to deal with it, any help will be appreciated, thanks.

**Comment by zaphoyd** [comment]
you are likely running into an issue whereby your browser does not trust the self signed example certificate distributed with WebSocket++. You will likely need to instruct your browser to trust the cert or procure a certificate that the browser trusts already.

**Comment by hs79hs** [comment]
Thanks for reply.
But the browser doesn't give me the chance to trust the cert, e.g. it doesn't pop a window to let me choose whether I trust the cert.
And I also try libwebsockets, which is another websocket library written in C, by using the cert it provided, it's ok. Only at the first time I need to choose that I trust the cert. 
I also try the cert provided by libwebsockets in websocketpp, it has the same problem too.

**Comment by hs79hs** [comment]
I have tried other browsers like IE and Edge, the error message turns to:

on_tls_init called with hdl: 0x1ae9d70
using TLS mode: Mozilla Intermediate
[2015-09-03 08:22:40] [error] handle_transport_init received error: TLS handshake failed
[2015-09-03 08:22:40] [fail] WebSocket Connection [::ffff:123.123.98.120]:36279 - "" - 0 websocketpp.transport.asio.socket:8 TLS handshake failed

**Comment by hs79hs** [comment]
I also try to track the code related to this error, but it turns to when handle_read_handshake() (in impl/connection_impl.hpp) is called, the parameter 'ec' already has error code, I don't know who calls handle_read_handshake() and how to continue to debug...

**Comment by hs79hs** [comment]
Can anyone give me some examples or instructions to run in wss connection? Thanks.

**Comment by hs79hs** [comment]
Yes, you're right, it's really because the browser doesn't support the self-signed certificate :-)
But it doesn't give a hint to remind the user.
By accessing e.g. https://IP:9002 and select to trust the certificate, then it works.
Thanks again, using websocket++ gives me good experience and saves me lots of time :-)
