### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by chelinho139** [zaphoyd/websocketpp#469]
Hi, we are getting segmentation fault signal  and the backtrace from gdb says:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 3144.0xd88]
0x0000000000461084 in websocketpp::processor::hybi13<websocketpp::config::asio>::consume(unsigned char*, unsigned long long, std::error_code&) ()

Here is our code:

void WebServer::OnRead(ConnectionWebsocket* connection, websocketpp::connection_hdl hdl, websocketpp::server<websocketpp::config::asio>::message_ptr msg){
	try{
		memcpy(connection->inBuff, msg->get_payload().c_str(), inMsgLength);
//		std::cout << "Msg Received: "<< connection->inBuff << std::endl;
		actionResolver->solveMessage(connection, this->mutexWorld);
	}catch(...){
		std::cout << "Excepcion en OnRead"<< std::endl;
	}
}

We have no idea what that consume function does, but please any help???

**Comment by tkarls** [comment]
I had the same problem and found the fix here:
https://github.com/zaphoyd/websocketpp/issues/395

See  if that helps you too.

**Comment by zaphoyd** [comment]
as of 0.7.0 you shouldn't need to #define anything special to avoid this.
