### ISSUE TITLE
Using c++11 only, not boost; which file to include?

### ISSUE THREAD

**Issue by astoeckley** [zaphoyd/websocketpp#474]
I am trying the example here:

http://www.zaphoyd.com/websocketpp/manual/building-program-websocket

I am using C++14 on Mac OSX. I am not using Boost. When I follow this example exactly, it tells me that boost/version.hpp was not found in asio.hpp. 

Since this will probably come up again as I work through other examples, how do I know which files to include if I am definitely not going to be using boost?

**Comment by zaphoyd** [comment]
To use standalone Asio rather than Boost Asio, define `ASIO_STANDALONE` before any WebSocket++ or Asio headers are included. You'll also need to make sure you are building in C++11 (or later) mode.

**Comment by astoeckley** [comment]
Thanks. I noticed that if I changed these two lines on the example of that page, I could compile file (though am still learning how to use it). Is this also a good approach?

#include <websocketpp/config/core.hpp>

typedef websocketpp::server<websocketpp::config::core> server;

**Comment by zaphoyd** [comment]
The core profile does not use Asio or Boost. If you build a system using that config you will have to supply your own network & timer code. This may or may not be what you want.

If you want Asio supplied networking without Boost, use the original includes with the `ASIO_STANDALONE` define (and make sure the Asio standalone headers are in your include path).
