### ISSUE TITLE
Confusion over Asio headers

### ISSUE THREAD

**Issue by hellofunk** [zaphoyd/websocketpp#475]
There seems to be contrary opinions about how Asio without Boost works, whether you actually need Boost headers or not:

http://stackoverflow.com/questions/33544090/how-to-use-asio-standalone-in-xcode-c11-without-boost?noredirect=1#comment54895093_33544090

If you can shed some light on this, I'd appreciate it. If it's possible to include only some Asio headers to use websocketpp, that's great. But Boost's Asio has a dependency on Boost System, which requires building the Boost binaries, so it is not header-only. I've built them once before and it takes many hours to do so, and if it's the only reason I'm using Boost, I'd prefer to not to use Boost at all if there is an alternative.

**Comment by zaphoyd** [comment]
I've answered that question. With respect to WebSocket++ in particular, the exact same steps apply. WebSocket++ looks for the `ASIO_STANDALONE` define and the `-std=c++11` flags to autodetect whether it should use the Boost or standalone version of Asio.

A note about building the Boost libraries:
- Check your package manager, many have pre-build binaries that can be installed in seconds
- If you are on a multi-core system you can build Boost in parallel. On my 4 core 2013 laptop I can build all of boost in ~3 minutes
- You can ask boost to only build the libraries you are using. If you are only using Boost System, the compile is instantaneous, as it is a very small library.

**Comment by hellofunk** [comment]
Thank you very much for the explanation. But I am amazed at the number you mention for Boost compilation. I followed the instructions here:

http://www.boost.org/doc/libs/1_59_0/more/getting_started/unix-variants.html#easy-build-and-install

On my 3-year old Macbook Pro which is pretty fast, has lots of RAM and an SSD, it took me 5 hours today to build all of Boost! I wasn't explicitly stating anything as parallel but even if I had, I can't image doing it only 3 minutes. You must be using a different compilation strategy that the one listed on boost's site?

**Comment by hellofunk** [comment]
This is getting off topic, so I've posted another question here:

http://stackoverflow.com/questions/33566782/building-all-of-boost-in-a-few-minutes

Thanks for the help.
