### ISSUE TITLE
Using get_remote_endpoint()

### ISSUE THREAD

**Issue by anarendil** [zaphoyd/websocketpp#481]
Hello! I tried to use broadcastserver example, and I need get client ip-adress. I found this this issue - https://github.com/zaphoyd/websocketpp/issues/422 and I tried do this:
void on_open(connection_hdl hdl) {    		
        server::connection_ptr con = m_server.get_con_from_hdl( hdl );    		
        unique_lock<mutex> lock(m_action_lock);             
        m_actions.push(action(SUBSCRIBE,hdl));
        lock.unlock();
        m_action_cond.notify_one();
    }
This code is compiling without errors, but this is not transport_con_ptr, with I find in websocketpp/transport/stub/endpoint.hpp. And when I : 
#include <websocketpp/transport/stub/endpoint.hpp>
and try:
websocketpp::transport::stub::endpoint::transport_con_ptr con=m_server.get_con_from_hdl( hdl );
instead "server::connection_ptr con = m_server.get_con_from_hdl( hdl );"
but g++ show this:
"broadcastserver.cpp: In member function 'void broadcast_server::on_open(websocketpp::connection_hdl)':
broadcastserver.cpp:84:37: error: 'template<class config> class websocketpp::transport::stub::endpoint' used without template parameters
       websocketpp::transport::stub::endpoint::transport_con_ptr con=m_server.get_con_from_hdl( hdl );"

**Comment by zaphoyd** [comment]
con->get_remote_endpoint() in your open handler will work fine. `con` in your case is a subclass of the transport connection type so the method is available.

websocketpp::transport::stub is a non-functional skeleton class to demonstrate which methods are necessary to implement your own. Unless you are building a custom transport you can ignore it.

Finally, for best results in the future, library usage questions should be directed to the mailing list at websocketpp@googlegroups.com.
