### ISSUE TITLE
Perhaps a malformed path

### ISSUE THREAD

**Issue by giachi** [zaphoyd/websocketpp#491]
Hi !!!

Perhaps a malformed path in "websocketpp/common/asio_ssl.hpp" line 32
websocketpp v 0.6.0 && 0.7.x dev

```cpp
#ifdef ASIO_STANDALONE
    #include <asio/asio/ssl.hpp> // error
#else
    #include <boost/asio/ssl.hpp>
#endif
```
```cpp
#ifdef ASIO_STANDALONE
    #include <asio/ssl.hpp> // ok
#else
    #include <boost/asio/ssl.hpp>
#endif
```

Gérard

**Comment by Meoo** [comment]
I had to do the exact same modification to fix my build.

**Comment by zaphoyd** [comment]
I've pushed an update to the develop branch that should fix this. Can you confirm?

**Comment by Meoo** [comment]
Works for me

**Comment by giachi** [comment]
Hi
Excuse my Google english

It's ok now.

I have a question : Websocketpp 0.7x dev "permessage-deflate extension"
work fine.

is there a way to disable it (or change the configuration) while the
program runs ?

thank you very much

2015-12-20 15:38 GMT+01:00 Peter Thorson <notifications@github.com>:

**Comment by zaphoyd** [comment]
@giachi I'd be happy to discuss the config and use of the deflate/compression extension on the project mailing list (websocketpp@googlegroups.com). I'd rather keep the Github issues queue strictly for code issues rather than usage questions.

**Comment by giachi** [comment]
Ok, thanks, i transfer the question
