### ISSUE TITLE
How does the async nature of the server work?

### ISSUE THREAD

**Issue by astoeckley** [zaphoyd/websocketpp#504]
I have a fundamental question about how a server handles incoming requests.

I have a project that basically accepts a request from a client, does some heavy computation, then sends something back to the client. I am not myself using any threading on the server-side, but I understand that websocketpp is in fact processing requests asynchronously, is this correct? If the server receives a request while it is still processing another request, is that request also processed simultaneously, or does it wait for the first to complete?

**Comment by zaphoyd** [comment]
I'd be happy to answer this question on the mailing list (websocketpp@googlegroups.com). I prefer to keep the issue queue for bugs/problems with the software itself and use the mailing list for usage questions that might be relevant to others and need to be more easily discoverable in the future.

**Comment by astoeckley** [comment]
No, problem at all, many thanks!
