### ISSUE TITLE
Deadlock in endpoint destructor

### ISSUE THREAD

**Issue by apronchenkov** [zaphoyd/websocketpp#510]
Destructor of the m_work in websocketpp/transport/asio/endpoint.hpp tries to access destroyed m_io_service after the last one was already deleted in the ~endpoint().

**Comment by zaphoyd** [comment]
I can see the problem, the `io_service` is destroyed before the work object that references it. The solution is obvious (don't do that). I can't actually reproduce a crash, deadlock, or other problematic behavior though. Do you have a simple example that does that?

**Comment by apronchenkov** [comment]
For me it was something like this:
``` c++
#include <future>
#include <vector>
#include <websocketpp/client.hpp>
#include <websocketpp/config/asio_no_tls_client.hpp>

int main() {
  websocketpp::client<websocketpp::config::asio_client> service;
  service.init_asio();
  service.start_perpetual();
  std::vector<std::future<void>> workers(1);
  for (auto& worker : workers) {
    worker = std::async(std::launch::async, [&]{ service.run(); });
  }
  service.stop();
  for (auto& worker : workers) {
    worker.get();
  }
  // service.stop_perpetual();
  return 0;
}
```

**Comment by zaphoyd** [comment]
I still haven't been able to reproduce this issue. I've committed a fix to the develop branch that is likely to help with it though. Would you be able to test that?

**Comment by apronchenkov** [comment]
It looks ok.
