### ISSUE TITLE
Simple client application?

### ISSUE THREAD

**Issue by fheinrich** [zaphoyd/websocketpp#515]
Hi,

I need a really simple c++ client example and I cant find one.

It should do:
1. Connect with server (i already set up a nodejs server for this)
2. Send a string to the server
3. Receive an answer from the server

Based on the answer I wanna do some things in my c++ program then...

May you provice me some help with this? Thanks in advance.

**Comment by minexew** [comment]
https://github.com/zaphoyd/websocketpp/blob/master/examples/testee_client/testee_client.cpp ?

**Comment by fheinrich** [comment]
Thx. I have now tried to implement this example into my oop project. This is what I have:

`#ifndef WebsocketClient_H
#define WebsocketClient_H

#include <websocketpp/config/asio_no_tls_client.hpp>
#include <websocketpp/client.hpp>

#include <iostream>

typedef websocketpp::client<websocketpp::config::asio_client> client;

using websocketpp::lib::placeholders::_1;
using websocketpp::lib::placeholders::_2;
using websocketpp::lib::bind;
using namespace std;

// pull out the type of messages sent by our config
typedef websocketpp::config::asio_client::message_type::ptr message_ptr;

class WebsocketClient
{

public:
	WebsocketClient();
	void on_message(client* c, websocketpp::connection_hdl hdl, message_ptr msg);

private:
	int case_count = 0;

};

#endif`


and

`#include "WebsocketClient.h"

WebsocketClient::WebsocketClient()
{
	// Create a server endpoint
	client c;

	std::string uri = "ws://localhost:9001";

	try {
		// We expect there to be a lot of errors, so suppress them
		c.clear_access_channels(websocketpp::log::alevel::all);
		c.clear_error_channels(websocketpp::log::elevel::all);

		// Initialize ASIO
		c.init_asio();

		// Register our handlers
		c.set_message_handler(bind(&on_message, &c, ::_1, ::_2));

		websocketpp::lib::error_code ec;
		client::connection_ptr con = c.get_connection(uri + "/getCaseCount", ec);
		c.connect(con);

		// Start the ASIO io_service run loop
		c.run();

		std::cout << "case count: " << case_count << std::endl;

		for (int i = 1; i <= case_count; i++) {
			c.reset();

			std::stringstream url;

			url << uri << "/runCase?case=" << i << "&agent="
				<< websocketpp::user_agent;

			con = c.get_connection(url.str(), ec);

			c.connect(con);

			c.run();
		}

		std::cout << "done" << std::endl;

	}
	catch (websocketpp::exception const & e) {
		std::cout << e.what() << std::endl;
	}
}

void WebsocketClient::on_message(client* c, websocketpp::connection_hdl hdl, message_ptr msg)
{
	client::connection_ptr con = c->get_con_from_hdl(hdl);

	if (con->get_resource() == "/getCaseCount") {
		std::cout << "Detected " << msg->get_payload() << " test cases."
			<< std::endl;
		case_count = atoi(msg->get_payload().c_str());
	}
	else {
		c->send(hdl, msg->get_payload(), msg->get_opcode());
	}
}`

And i'm getting the following errors:

`Fehler	1	error C2276: '&': Ungültige Operation auf Ausdruck einer gebundenen Memberfunktion	C:\Users\SVARTBERG\Documents\Visual Studio 2013\Projects\svrtPrivate\svrtPrivate\WebsocketClient.cpp	19	1	svrtPrivate
Fehler	2	error C2660: 'bind': Funktion akzeptiert keine 4 Argumente	C:\Users\SVARTBERG\Documents\Visual Studio 2013\Projects\svrtPrivate\svrtPrivate\WebsocketClient.cpp	19	1	svrtPrivate
`

(invalid operation on expression of a bound member function)
("bind" doesnt accept 4 parameters)

**Comment by zaphoyd** [comment]
The error is exactly what it suggests. bind in your case needs 5 parameters because you are binding to a member function and not a free function. A member function bind will need an extra pointer to the instance of the class.

Check out the examples section here:
http://en.cppreference.com/w/cpp/utility/functional/bind
there is a section for "bind to a member function"

In the future could you use the mailing list (websocketpp@googlegroups.com) or usage related questions?
