### ISSUE TITLE
failed to build websocket++ on ScienticLinux 7

### ISSUE THREAD

**Issue by anomalouscowherd** [zaphoyd/websocketpp#527]
Hi guys.  I'm not sure exactly what I want here.  I am looking for a websockets client.  I got one to work
https://github.com/progrium/wssh
but it uses an out of date library and is no longer maintained.
My first question is: Can I use the debug client like so:
wssh wss://api.stockfighter.io/ob/api/ws/REDACTED/venues/FVBTEX/tickertape/stocks/ENYO
which produces output like this:

T 127.0.0.1:43688 -> 127.0.0.1:4434 [AP]
GET /ob/api/ws/REDACTED/venues/FVBTEX/tickertape/stocks/ENYO HTTP/1.1.
Host: 127.0.0.1.
Connection: Upgrade.
Upgrade: websocket.
Sec-WebSocket-Key: pQ7NLbPHAqEnyJqxnGoTWw==.
Origin: wss://127.0.0.1:443/ob/api/ws/REDACTED/venues/FVBTEX/tickertape/stocks/ENYO.
Sec-WebSocket-Version: 13.
.

##
T 127.0.0.1:4434 -> 127.0.0.1:43688 [AP]
HTTP/1.1 101 Switching Protocols.
Server: nginx/1.8.0.
Date: Sun, 14 Feb 2016 12:16:13 GMT.
Connection: upgrade.
Upgrade: websocket.
Sec-WebSocket-Accept: TaQmfswNWOs5sZ6tchGXkIzbb3w=.
.

T 127.0.0.1:4434 -> 127.0.0.1:43688 [AP]
.~..{"ok":true,"quote":{"symbol":"ENYO","venue":"FVBTEX","ask":6326,"bidSize":0,"askSize":11478,"bidDepth":0,"askDepth":22956,"last":6233,"lastSize":180,"lastTrade":"2016-02-14T12:14:25.905517132Z","quoteTime":"2016-02-14T12:14:30.825880606Z"}}

(That's ngrep output not what the program spits out.)

Question two: How do I get this thing to build?  I installed boost from yum and fussed with BOOST_LIBS and includes, but this is what I see now:

[root@sl7-vm websocketpp-master]# scons
scons: Reading SConscript files ...
C++11 build environment partially enabled
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [build/release/broadcast_server/broadcast_server] Implicit dependency `/usr/lib64/stage/lib/libboost_system.a' not found, needed by target `build/release/broadcast_server/broadcast_server'.
scons: building terminated because of errors.

The file it is looking for is here:
/usr/lib64/libboost_system.a
I guess I can create a symlink to the location it is looking for, but that seems lame.  Can I use the scons build system to automatically detect the correct location?  Incidentally it looks like it only wants static libraries.  I was able to install those from an RPM. It would be cool if an RPM existed for this library that worked out of the box on a redhat system ( or a .deb for ubuntu etc.) That would save a lot of support requests.

Third question: Is there a (well maintained ) program ( in C or C++ ) that works like wssh? I have tried to use socat for this, but it  stops after the handshake.

**Comment by zaphoyd** [comment]
Closing this as as these usage related questions were answered on IRC.
