### ISSUE TITLE
Send serialized objects

### ISSUE THREAD

**Issue by gustavomassa** [zaphoyd/websocketpp#533]
Hello, I'm new to Websocket++, this is a wonderful library, thank you for the great job.

I would like to know if this library has any internal method to send an entire object serialized.
I know that I can send strings, void * and message_ptr, can I serialize objects using void* or message_ptr? Or I should use a Json library to serialize the object and then send the serialized object as string?

Thank you!

**Comment by zaphoyd** [comment]
Object serialization is out of scope for WebSocket++. JSON, protocol buffers, and msgpack are common options users of the library have used in the past.

For future usage related questions, the mailing list (websocketpp@googlegroups.com) is preferred for non-bug report/feature requests.
