### ISSUE TITLE
Beyond C++ [ C API, dynamic link library]

### ISSUE THREAD

**Issue by LeslieOnGithub** [zaphoyd/websocketpp#542]
Hi,
I am not a C++ guy , yet I have kept coming back to check on the progress of websocketpp for quite a while hoping that one day I might be able to use it . I started to look into it, but then it occurred to me that it would greatly extend the usability of the project if it contained a  C API and/or a project ready to be compiled as a dynamic link library.  So why not ask the author to  create them if possible. :)

**Comment by zaphoyd** [comment]
WebSocket++ provides a native C++ interface with C++ exclusive features. A shared/dynamically linked library with a C API would be a completely different project in a completely different language. If you are interested in such a library I would recommend libwebsockets.
