### ISSUE TITLE
Getting host address

### ISSUE THREAD

**Issue by nokome** [zaphoyd/websocketpp#543]
I am attempting to get the host address using `get_local_endpoint` (see #458). But I'm getting "::" as the local address when I was expecting "127.0.0.1" or similar.

My test code is:
```
#include <iostream>

#include <websocketpp/config/asio_no_tls.hpp>
#include <websocketpp/server.hpp>

typedef websocketpp::server<websocketpp::config::asio> server;

int main() {
	server s;
	s.init_asio();
	s.listen(9002);
	s.start_accept();

	websocketpp::lib::asio::error_code error;
	auto endpoint = s.get_local_endpoint(error);
	if (error) {
		std::cerr<<"error getting local endpoint";
	}
	std::cout<<endpoint.address()<<"\t"<<endpoint.port()<<std::endl;

	s.run();
}
```
Compiling and running this on Ubuntu 14.04 outputs:
```
::	9002
```
Apologies in advance if I'm missing something basic here.

**Comment by zaphoyd** [comment]
By default WebSocket++ listens on the unspecified address (https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address). This is a special address that means, effectively, "listen on all address families (IPv4, IPv6), all interfaces (lo, eth0, eth1, etc), and all addresses those interfaces have."

The unspecified address's address is `::`. Note that this isn't actually a valid address, it is just a placeholder that refers to the unspecified address. The local endpoint on the server object will never get a concrete address. The actual socket associated with each connection will. Once a connection is established you can retrieve the exact local address there.

There are other overloads of server::listen that allow you to listen on a specific address family or specific address if you don't want the listen everywhere behavior.

**Comment by nokome** [comment]
Thanks @zaphoyd for taking the time to explain that - I was missing something basic. In case others find it of use, this is what I ended up using in my connection handler:

```
	server::connection_ptr connection = server_.get_con_from_hdl(hdl);
	auto local_endpoint = connection->get_raw_socket().local_endpoint();
	std::string local_address = local_endpoint.address().to_string();
```
