### ISSUE TITLE
How to close connection properly?

### ISSUE THREAD

**Issue by ejkoy** [zaphoyd/websocketpp#545]
> void on_open(server\* s, websocketpp::connection_hdl hdl) {
>     s->close(hdl, websocketpp::close::status::going_away, "");
> }

When I do close connection, always show an error message:

> [2016-04-12 12:41:09] [info] asio async_read_at_least error: system:10058 ()
> [2016-04-12 12:41:09] [error] handle_read_frame error: websocketpp.transport:2 (
> Underlying Transport Error)

Is this properly?

**Comment by zaphoyd** [comment]
Probably? WebSocket++ will catch and de-escalate known expected "errors", such as end of file when we are expecting the connection to end. This particular error code is not one I am familiar with and looks like it might be from an operating system I can't immediately identify. Can you shed some light on your build environment? Are you using Boost Asio or standalone? C++11 STL or Boost? What OS, what compiler?

For more general reference on closing a connection properly refer to the FAQ question (http://docs.websocketpp.org/faq.html) "How do I cleanly exit an Asio transport based program".

**Comment by SzAmmi** [comment]
Do:
```c++
m_server.pause_reading(hdl); // <-- THIS LINE FIXES THE ERROR
m_server.close(hdl, code, "");
```
It worked for me :)
