### ISSUE TITLE
Would you integrate this cadabra2 patch: get_acceptor()

### ISSUE THREAD

**Issue by yurivict** [zaphoyd/websocketpp#560]
Cadabra project bundled websocketpp-0.6.0 with the only difference being an addition of get_acceptor() method: https://github.com/kpeeters/cadabra2/blob/master/client_server/websocketpp/transport/asio/endpoint.hpp

They use it to obtain the endpoint port:
```
                auto p = wserver.get_acceptor()->local_endpoint();
                std::cout << p.port()  << std::endl;
```

Would you think this is a good patch, and would you integrate it? Or what is the right way to do what cadabra2 is doing?

Thanks!

**Comment by zaphoyd** [comment]
The correct replacement for this would be to use endpoint::get_local_endpoint (https://docs.websocketpp.org/singletonwebsocketpp_1_1transport_1_1asio_1_1endpoint.html#a4147ba098fc2f1669d2f880b47917342 )

Example:

```
auto p = wserver.get_local_endpoint();
std::cout << p.port() << std::endl;
```

No changes to the library core would be needed. Note: this method was first available in 0.7.0 so the currently bundled 0.6.0 would need to be upgraded first (I would recommend doing so).

**Comment by kpeeters** [comment]
I have upgraded to 0.7.0. As explained earlier, I do not want to unbundle, as that leads to dependency hell on OS X and several Linux distributions that do not have websocketpp (or do not have the right version).

**Comment by yurivict** [comment]
Ok, thanks!

**Comment by yurivict** [comment]
@kpeeters Please consider taking advantage of git submodule feature to bundle websocketpp: https://git-scm.com/docs/git-submodule
