### ISSUE TITLE
about -std=c++0x

### ISSUE THREAD

**Issue by lwba21190** [zaphoyd/websocketpp#562]
Dear zaphoyd,
       I am test your wensockets++ project. But I must compile my project with -std=c++0x because of the use of "start_accept()" . So how can I compile my project without -std=c++0x? How can I make my project depends on Boost but not C++11? Thank you !

**Comment by zaphoyd** [comment]
As long as you don't explicitly compile in C++0x/11/14/17 mode and don'e define the 'force use of c++11 option (`_WEBSOCKETPP_CPP11_STL_`) then WebSocket++ should build in C++03 compatibility mode. This will automatically select Boost alternatives to the C++11 libraries otherwise needed.

**Comment by lwba21190** [comment]
Thank you!  I have solved this problems!
