### ISSUE TITLE
handle_read_frame error: websocketpp.transport:7 (End of File)

### ISSUE THREAD

**Issue by SzAmmi** [zaphoyd/websocketpp#580]
Sometimes when browser closes connection to my websocketpp server, I get:
```
[2016-09-09 19:40:53] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
```

How I can fix it?

**Comment by SzAmmi** [comment]
Sometimes I get:
```
[2016-09-14 15:44:40] [info] asio async_read_at_least error: system:10054 (An existing connection was forcibly closed by
 the remote host)
[2016-09-14 15:44:40] [error] handle_read_frame error: websocketpp.transport:2 (Underlying Transport Error)
```

**Comment by zaphoyd** [comment]
This is usually the result of the browser uncleanly closing the connection. There generally isn't anything you can do about it on the server end. It may indicate a bug in the client or it may be on purpose because the client doesn't want to expend the resources to perform a clean shutdown.

**Comment by ashubhatt** [comment]
I am facing the same issue.
I have been using the latest release 0.8.1.

I have created a WebSocket server which crashes after multiple unclean closed connections from the client.
```
[2019-08-23 16:50:46] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
```

I have tested the same using a dummy JS code which uncleany closes the connection with Server. It takes about 12 uncleanly closed connections before it completely crashes.

Crash logs:
```
[2019-08-23 17:02:27] [info] asio handle_accept error: asio.system:24 (Too many open files)
[2019-08-23 17:02:27] [info] Error getting remote endpoint: asio.system:9 (Bad file descriptor)
[2019-08-23 17:02:27] [info] asio async_shutdown error: asio.system:9 (Bad file descriptor)
```

Do we have any solution to clean-up the uncleanly-closed connections, so that the corresponding file descriptors are also closed from asio?

**Comment by cyrusbehr** [comment]
I get a similar error, and it causes my system to crash.
When a client uncleanly exits, I will get the following error message `[2020-06-26 09:38:05.566] [trueface_temp_reader_ASIO] [error] handle_read_frame error: websocketpp.transport:7 (End of File)`
After a few of these, my program crashes with the following exception: 
`# terminate called after throwing an instance of 'std::system_error'
  what():  remote_endpoint: Transport endpoint is not connected`
How can I prevent the program from crashing. Any updated @zaphoyd

**Comment by gouchaoer** [comment]
same problem

**Comment by weiguang-zz** [comment]
same problem:
```
[2020-09-09 10:41:01] [disconnect] Disconnect close local:[1006,End of File] remote:[1001]
[2020-09-09 10:41:01] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
Signal: SIGSEGV (Segmentation fault)
```

**Comment by cyrusbehr** [comment]
My workaround is the following:
```
void TelemetryServer::run() {
    for (;;) {
        try {
            m_endpoint.run();
            break; // run() exited normally
        } catch (websocketpp::exception const & e) {
            m_logger->error(e.what());
            m_logger->error("Exception thrown from m_io_service->run(). Restarting m_io_service->run()");
        } catch (...) {
            m_logger->critical("Hit critial error. Restarting m_io_service->run()");
        }
    }
}
```

Where `m_endpoint` is of type `websocketpp::server<custom_config>` and `custom_config` extends `websocketpp::config::asio`

**Comment by erikzenker** [comment]
Could you have a look who throws the exception with gdb, lldb or clang asan?

**Comment by machacd** [comment]
How can I detect this very error in a client? I only see it in stdout, but it does not trigger neither on_fail nor on_close.

**Comment by Aries1989** [comment]
same error。help！

**Comment by tnie** [comment]
same problem

**Comment by folery** [comment]
Same issue. We cannot control all clients connecting to the server, and some clients may lose connection because of network which is not rare. Is there a solution that we can clean the uncleanly-closed connections instead of crashing that all other connections fail?

**Comment by Aries1989** [comment]
@folery have you solute that problem?

**Comment by guoh27** [comment]
how to disable print this error message.

**Comment by npodonnell** [comment]
I had this problem too, with Qt websockets client. It seems to happen about 4/5 times when the client initiates the close. The problem (with Qt) may be the same or similar to what's described [here](https://mcguirev10.com/2019/08/17/how-to-close-websocket-correctly.html)

Anyway, my solution was to have the client send a "Goodbye" message then have the server initiate the close. So long as the client program isn't misbehaving, it should always be possible to send a "Goodbye" message. If there's network issues, the close may not work properly regardless of whether it's correctly implemented on the client side. So in my view this makes sense.
