### ISSUE TITLE
Wrong examples, possible wrong documentation

### ISSUE THREAD

**Issue by heretic13** [zaphoyd/websocketpp#584]
Source code
https://github.com/zaphoyd/websocketpp/blob/master/examples/echo_server/echo_server.cpp

and possible other example sources.

Lines:
try {
        s->send(hdl, msg->get_payload(), msg->get_opcode());
    } catch (const websocketpp::lib::error_code& e) {
        std::cout << "Echo failed because: " << e
                  << "(" << e.message() << ")" << std::endl;
    }

send thowing websocketpp::exception, not websocketpp::lib::error_code

**Comment by zaphoyd** [comment]
Yep this was wrong. I've pushed a commit to develop branch that fixes it.
