### ISSUE TITLE
No such file or directory found

### ISSUE THREAD

**Issue by sacOO7** [zaphoyd/websocketpp#605]
print_server.cpp:3:46: fatal error: websocketpp/config/asio_no_tls.hpp: No such file or directory
 #include <websocketpp/config/asio_no_tls.hpp>

Program gives above problem when I try to compile g++ print_server.cpp -I /home/sachin/websocketpp/
from https://www.zaphoyd.com/websocketpp/manual/building-program-websocket. I have added websocketpp under path , still giving me error.
Please provide me with proper documentation on how to compile program. I have searched everywhere but nothing was useful .

**Comment by xielinjiang** [comment]
include_directories(${CMAKE_SOURCE_DIR}/src)

**Comment by Pradeep2898** [comment]
Where we have to put this? which file?
