### ISSUE TITLE
Document on a basic send

### ISSUE THREAD

**Issue by Sweetkubuni** [zaphoyd/websocketpp#609]
I haven't found anything on sending a custom string as a reply. I think I have to do the following : 

				server::connection_ptr con = m_server.get_con_from_hdl(hdl);
				std::string resp("BAD");
				con->send(resp, websocketpp::frame::opcode::text);
would this happen to be correct? can the documents be updated to reflect how to send text and binary?

thank you!

**Comment by NuclearC** [comment]
well i think you need to do:
```C++
ws.send(con, "BAD", websocketpp::frame::opcode::TEXT);
```
Where ws is your websocketpp::client or websocketpp::server object, and con is connection_ptr

**Comment by zaphoyd** [comment]
@NuclearC is correct

`endpoint.send(hdl, "BAD", websocketpp::frame::opcode::binary);`

can be used to send binary messages
