### ISSUE TITLE
No member named `run`

### ISSUE THREAD

**Issue by jeffersoncarpenter** [zaphoyd/websocketpp#621]
Hey, I've got the code

```
#include <websocketpp/config/core.hpp>
#include <websocketpp/server.hpp>

typedef websocketpp::server<websocketpp::config::core> WebsocketServer;

int main() {
	WebsocketServer server;

	server.run();
}
```

based on this example: https://www.zaphoyd.com/websocketpp/manual/building-program-websocket

But I'm getting a compile error saying that `WebsocketServer` has no member named `run`.

**Comment by zaphoyd** [comment]
The run member function is provided by the Asio based transport. In the example code you are using the core config which uses the raw/iostream transport.

If you want to use run (which runs Asio's io_service event loop) you will need to use the Asio transport. If you definitely want to use the raw/iostream transport you will need to provide your own event loop.
