### ISSUE TITLE
bazel integration

### ISSUE THREAD

**Issue by alexflint** [zaphoyd/websocketpp#628]
How can I integrate this with a project using bazel as the build system?

**Comment by zaphoyd** [comment]
I am not familiar with the bazel build system. Generally, the process for integrating it is similar to other C++ libraries: Make sure the WebSocket++ headers are in your build system's include path and make sure any binary libraries are in the linking path.

WebSocket++ is a header only library so there are no libraries to build or link to directly. Depending on whether you have C++11 available or are using extra features (TLS, compression, Asio) there may be additional dependencies with their own headers/binary libraries to link.

If you have a specific issue (determining what features you are using and precisely which dependencies are necessary) the mailing list at websocketpp@googlegroups.com is the best place to ask.
