### ISSUE TITLE
Core examples?

### ISSUE THREAD

**Issue by aespielberg** [zaphoyd/websocketpp#629]
Hi all,

I'm excited about this project, however, I'm finding that I'm having a hard time using it.  I was excited about a potential boostless c++ websocket server implementation.  But, there are no examples using the boostless interface, and the API is different depending on which server type is being used.  For instance, some template types have no .listen function, which is important.   Is there any way to see an example for the broadcast server or a similar class in boostless mode?

**Comment by zaphoyd** [comment]
All of the Asio based examples can be used with or without boost, so there are no non-boost specific Asio examples. There are more details about using the Asio transport without boost in the FAQ https://docs.websocketpp.org/faq.html

See the questions about "can websocket++ be used without boost" and "can websocket++ be used with standalone Asio" questions.
