### ISSUE TITLE
Error: Underlying transport protocol

### ISSUE THREAD

**Issue by AngryLemonn** [zaphoyd/websocketpp#640]
Hi,

I am having a singular error with this library. Sometimes, when my program starts, the websocket server crash trying to listen on a port. The error is: **"Underlying transport protocol"**. This error happens randomly, but always after close and open again the websocket server.

When my websocket starts, this code is executed:
```
_server.set_reuse_addr ( true );
_server.listen ( port );

// ...

_server.run ();

// ...
```
And when the program finishes, this code is executed:
```
_server.stop_listening ();

// close connections...

_server.stop ();
```

I thought that the error could be listen on a locked port, but the flag "reuseaddr" is enabled, and only my websocket server listen on that port...

Any idea?

Regards,
J. A.

**Comment by zaphoyd** [comment]
Take a look at the FAQ section at https://docs.websocketpp.org/faq.html on cleanly closing an Asio transport based program.

The most likely problem here is the use of `endpoint::stop`, which is a forceful, immediate, and unclean halting of the entire event loop. This method is not required in normal usage of WebSocket++.

Additionally, regarding "underlying transport protocol" errors: The transport layer of the library is only loosely coupled with the core so when there is a problem at the transport level all the core knows is "something went wrong at the transport level" and you get a generic "underlying transport protocol error". Generally, in these cases, the transport layer will write its own more specific error to the error log (often at a lower log level like info or debug). Enabling lower level logging may get you the exact transport error.

**Comment by AngryLemonn** [comment]
@zaphoyd,  thank you for the response. I will try to not call "_server.close()" on my websocket server shutdown, I hope this solves the problem.

**Comment by AngryLemonn** [comment]
Works!!!
