### ISSUE TITLE
Chat Server with multiple "chatrooms" with websocketpp

### ISSUE THREAD

**Issue by Malachi0944** [zaphoyd/websocketpp#654]
Hi, I'm looking for some directions about the best way to implement a multiroom chat service. Searching the web didn't produce much help. 

I'm thinking along the lines of using the users connection resource, ie. /chatroom=xx/userid=xx

This would handled in the on validate method and then iterate through the current "chatrooms" to send the messages to the specific users associated with a room. 

Does this sound feasible?

thanks, 
Bryan

**Comment by zaphoyd** [comment]
There are lots of ways to do this. They aren't really in scope of the library itself.

A few usage suggestions:
The option you describe (auth in validate handler) is one popular option. The other is to exchange a hello/auth message as the first message on the connection.

Advantages of using validate+URL parameters:
- Reduces number of round trips to auth
- Lets you fast-reject situations where someone requests a chatroom or user that doesn't exist.
- Provides a simple way to capture authorized vs not as any connection that succeeds is assumed to be authorized.

Disadvantages:
- Makes it harder to support re-auth as a different user on the same connection
- Security/performance: validate handler is in the critical path and can't be handled asynchronously. If your auth processing code takes a long time and you want to support a lot of connections it may cause problems.
- Insecure: Sending authorization credentials/passwords as URL parameters are available to any function that has a connection handle, are included in the access logs, and are often seen/stored by HTTP proxy intermediaries.

Finally, I would recommend holding off on sending an entry message to other chatrooms until after the connection is successful (open handler not validate). This lets you do it asynchronously and keeps a potentially longer running operation (send O(n) messages) out of the synchronous validate handler.

**Comment by Malachi0944** [comment]
Thanks for the response to my question Zaphoyd. I managed to my service running quite nicely now. I do depreciate you taking the time to respond and giving me some pointers to think about.

cheers
