### ISSUE TITLE
std::auto_ptr doesn't exist in c++17, so memory.hpp no longer compiles

### ISSUE THREAD

**Issue by xaxxon** [zaphoyd/websocketpp#669]
https://github.com/zaphoyd/websocketpp/blob/master/websocketpp/common/memory.hpp#L68

causes:

```
/usr/local/include/websocketpp/common/memory.hpp:68:16: error: no member named 'auto_ptr' in namespace 'std'
    using std::auto_ptr;

```

**Comment by xaxxon** [comment]
I messed around a bit for how to get cmake to report on whether auto_ptr exists but couldn't find a simple, elegant solution

**Comment by xaxxon** [comment]
looking at the __cplusplus value might be a decent way to approach this, but I'm not sure.

**Comment by zaphoyd** [comment]
The develop branch has a fix for this already I believe, can you confirm that that works for you?

**Comment by zaphoyd** [comment]
Closing this unless someone confirms that the develop branch still has issues with C++17
