### ISSUE TITLE
I want to build websocketpp library without using boost, I ran the cmakelists.txt and make install but unable to locate the library. Will you specify the way I should follow?

### ISSUE THREAD

**Issue by Jigar27** [zaphoyd/websocketpp#670]

**Comment by zaphoyd** [comment]
WebSocket++ is a header only library. There is nothing to build. The scons and cmake files that are bundled with the library are for building the unit tests and example programs, many of which require boost for other reasons.

A program you write using WebSocket++ need not use boost unless you want to. More information about using WebSocket++ in your programs without boost and with standalone (non-boost) Asio can be found in the FAQ: https://docs.websocketpp.org/faq.html
