### ISSUE TITLE
Logging sent messages from client

### ISSUE THREAD

**Issue by risingsun007** [zaphoyd/websocketpp#671]
Is there anyway to log what messages are sent from the client.  I have a client which just receives data from a server, but using Wireshark I sees my client sends a lot of "requests" back to the server.  Is this communication from the client to the server part of the websocket protocol?

**Comment by zaphoyd** [comment]
Generally the WebSocket protocol will not send messages back to the server unless your client is explicitly sending them. If you are looking in Wireshark you may see the TCP stream acknowledgements being sent from the client back to the server. This is unrelated to the WebSocket protocol, but rather the TCP protocol that it is built on.

This page details how to enable various sorts of logging. You can ask WebSocket++ to log every message (including the complete message payload if desired)
https://docs.websocketpp.org/reference_8logging.html
