### ISSUE TITLE
Underlying Transport Error

### ISSUE THREAD

**Issue by GodBirdVista** [zaphoyd/websocketpp#674]
I use websocketpp in my program as websocket server.But recently in some users' environment when I listenning on some specific port,an error happened,I print the message of error_code,it's "Underlying Transport Error",Is that means the listening has prevented by some firewall on 3rd party security software?
The code is as below:
               std::error_code ec;
		server_->set_message_handler(boost::bind(&on_message, server_, ::_1, ::_2));
		server_->set_tls_init_handler(boost::bind(&on_tls_init,MOZILLA_INTERMEDIATE,::_1));
		server_->init_asio(ec);		
		server_->listen(2007 , ec);
after execute init_asio, there is no error returned,But after listen,the error appeared.
My English is not good, sorry for that,I hope I have describe the problem clearly.

**Comment by goodxianping** [comment]
ding yi xia

**Comment by garethsb-sony** [comment]
One possibility is that those environments do not support IPv6. To check this, use the three-argument version, server->listen(boost::asio::ip::tcp::v4(), 2007, ec);

**Comment by GodBirdVista** [comment]
Thank you ,I will try it.

**Comment by noirb** [comment]
This worked for me.
