### ISSUE TITLE
Error, invalid reserved bits

### ISSUE THREAD

**Issue by Werror** [zaphoyd/websocketpp#677]
I am facing the issue of websocketpp giving me the error of "invalid reserved bits" when using my own secure tcp socket implementation . I cannot find much information about this. Would provide some pointers? I think there is something wrong with binary blob I received from my socket.

**Comment by gentzel** [comment]
I'm getting the same error, but I'm not using a custom secure socket implementation, just asio::ssl.  This is with the current develop branch, Windows, VS2015.

My test application(s) work fine, but I'm getting this error when I incorporate the code into our main application.

**Comment by Werror** [comment]
I apologies, I actually found the problem, and fix.
The error is caused typically from integration with SSL, where you are not moving your read pointer by right amount of offset returned from SSL_read() (something like this) function, in a **non-blocking socket** since not all data is available at one time, and several iteration is required for 1 message read from websocket.

**Comment by Werror** [comment]
I will close this ticket now, since this is a integration issue.
@gentzel we can chat offline if help is needed.
