### ISSUE TITLE
Cancel Pending connection

### ISSUE THREAD

**Issue by mdavis777** [zaphoyd/websocketpp#702]
I have a system that has multiple websocket clients and servers sharing a bunch of json data.  I am creating unit tests to test the various error conditions and have noticed that if my client errors out and tries to close while the websocket is in connecting state it deadlocks.  The close is wrapped in a check for the connection being open then it joins the thread.  Since it doesn't call close the thread finally catches up and opens, but then never closes and joins.  

I just wanted to know if there was a safe command I can send while it is in the connecting state to cancel it, or should I wait until it gets to open and then follow the normally close path?

WebsocketClient::connection_ptr::terminate(websocketpp::error::operation_canceled)
seems to do what I need it to, but I don't know what the side effects of it are.

**Comment by zaphoyd** [comment]
Calling `connection::close` prior to an open handler should be avoided. Calling `close` in the open handler is a clean and non-protocol violating way of handling this case.. it obviously takes more time and resources though.

I haven't dug through the code to double check, but I suspect that `connection::terminate` would be "safe" to use during the open handshake. Safe in the sense that it shouldn't break your program. It is not particularly friendly to the remote endpoint which may or may not be an issue depending on what you are doing. Most likely side effect would be triggering os level timeouts or cooldowns on the ports in question on one or both endpoints.

**Comment by mdavis777** [comment]
Since this is just for automated unit exception testing as long as it is consistent and doesn't seg fault I am good with it.  Honestly I think it is failing before the remote endpoint is even started which is probably a reason it gets stuck in connecting for so long.  A simple 100ms sleep also gets it working, but I hate to rely on fixed times in unit tests since every machine is slightly different.

Thanks for the help.

**Comment by xuzhaofangxzf** [comment]
> Since this is just for automated unit exception testing as long as it is consistent and doesn't seg fault I am good with it. Honestly I think it is failing before the remote endpoint is even started which is probably a reason it gets stuck in connecting for so long. A simple 100ms sleep also gets it working, but I hate to rely on fixed times in unit tests since every machine is slightly different.
> 
> Thanks for the help.

have you found any solution, if so, please tell me
