### ISSUE TITLE
How to close the server correctly

### ISSUE THREAD

**Issue by xiaoyuit** [zaphoyd/websocketpp#704]
Could you tell me how to properly shut down the server, I use server.stop_listening (), server.stop (), and then call server.close (HDL) closed cycle, the next time you start the server cannot be enabled, invalid state will be thrown, and closed shut down the server server after restarting the server example?

**Comment by jacky8301** [comment]
I have the same problem!

**Comment by Rowandjj** [comment]
same problem... help wanted

**Comment by maksis** [comment]
I don't have a simple example but restarting works in my application.

Stopping: https://github.com/airdcpp/airgit/blob/51b042d2c58aa9cb7be89e6a09cec34e0efaec9f/airdcpp-webapi/web-server/WebServerManager.cpp#L349
Starting: https://github.com/airdcpp/airgit/blob/51b042d2c58aa9cb7be89e6a09cec34e0efaec9f/airdcpp-webapi/web-server/WebServerManager.cpp#L141

**Comment by zaphoyd** [comment]
There are detailed instructions on how to properly shut down a server in the FAQ (https://docs.websocketpp.org/faq.html) under "How do I cleanly exit an Asio transport based program".

In short: calling `stop_listening()` on your endpoint to stop new connections from being accepted then either wait until all existing connections close, or manually close them with `connection::close()`.

If you want a clean close, it is important that you *do not* call `endpoint::stop()` or the `stop()` method on the underlying Asio io_service. See the warning note in the FAQ entry for more details.
