### ISSUE TITLE
How to disconnect client when no message is received in 5 seconds?

### ISSUE THREAD

**Issue by alphasignal** [zaphoyd/websocketpp#720]
Hi,

I would like to know how the server can disconnect a connected client if that client does not send a message within a specific time period (ie. 5 seconds)?

Thanks

**Comment by zaphoyd** [comment]
There are two main options. If the transport you are using supports timers (such as the Asio transport) you can set a timer in your open handler, cancel the timer when you receive a message, and close the connection if the timer expires. The bundled `telemetry_server` example) has an example of setting timers when using the Asio based transport. If you are using a transport that doesn't support timers you can set up your own timer in another thread and do something similar.
