### ISSUE TITLE
std::auto_ptr and std::binary_function

### ISSUE THREAD

**Issue by jk-jeon** [zaphoyd/websocketpp#728]
Those are deprecated in C++11 and completely removed in C++17.
Usage of these causes recent C++17-conforming compilers to generate errors.
Please consider removing them.
I'm not 100% sure, but removing their uses seems not affect the whole library at all.

**Comment by zaphoyd** [comment]
`std::auto_ptr` is used only when the library is build in a pre-C++11 mode. This is done with preprocessor defines so a C++17 compiler building the library in C++11 or later mode should not be seeing them. If this is not the behavior you are seeing can you provide a few more details (what version/branch, which compiler, what location it is seeing auto_ptr, etc)

I can't find any usages of `std::binary_function` in the library. Can you point out where this is specifically?

**Comment by jk-jeon** [comment]
The issues was already fixed after #592. I was referring to an older version. Sorry.
