### ISSUE TITLE
Custom context with callback handlers

### ISSUE THREAD

**Issue by Merethiel** [zaphoyd/websocketpp#730]
I would like to store the websocketpp::connection_hdl in a class dedicated to each connection which holds extra information about the connection. In the on_open handler I can store each hdl in a new class but in the other handlers such as on_message and on_close, I would need to iterate through my container of connection objects until the corresponding hdl matches, then perform an update from there. But iterating through the container seems like too much overhead. Is there an easier way to do this? To allow a custom context tied to the hdl to be passed into the callback handlers?

**Comment by zaphoyd** [comment]
I remembered a third option for this. WebSocket++ allows you to assign custom callback handlers to each connection. With this you can use `std::bind` to attach additional parameters that will be included when your message or other handler is called.

**Comment by Merethiel** [comment]
Thank you for the response!

The first two options seem viable but I'm not fully grasping the third option. The handlers are set during the initialisation stage of the server, before any connections or objects are created. Should I assign the on_message callback during in the connecting callback and pass the context through bind? Because prior I was assigning the on_message callback before any connections were received.

**Comment by zaphoyd** [comment]
When a connection is created handlers set on the endpoint are copied to the new connection. You can update these handlers on a per connection basis any time from any of the other connection handlers.

In your open handler you can generate a context object and rebind the message handler to pass it in. The new handler will be used for future events.

**Comment by Merethiel** [comment]
Ah, that worked out brilliantly thank you!

One final Issue I have and I don't know if this is the right place to post it, I'm able to compile Websocketpp just fine on my Windows machine. But I receive an encoding error when I try to compile with XCode on my MacOS. I did try using vcpkg to install Websocketpp but there seems to be a lot of Unanswered bugs corresponding to vcpkg that haven't been answered or fixed. Has anyone mentioned the encoding issue compiling through XCode before? Is there a fix for this? Maybe a script that could go through all the files and quickly change the encoding?

This is the error I receive through XCode:
fatal error: UTF-16 (LE) byte order mark detected in '/Users/Merethiel/websocketserver/Server/Server.cpp', but encoding is not supported
1 error generated.
