### ISSUE TITLE
Compiling with XCode on MacOS 

### ISSUE THREAD

**Issue by Merethiel** [zaphoyd/websocketpp#733]
When I try to compile my source alongside websocketpp on XCode, I receive a linker error regarding boost_system. I do have boost compiled static but I think websocketpp wants the dynamic library version of boost_system.

This is the error:
merethielLd Build/Products/Release/Server normal x86_64
    cd /Users/merethiel/websocketserver
    export MACOSX_DEPLOYMENT_TARGET=10.13
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/merethiel/websocketserver/Build/Products/Release -F/Users/merethiel/websocketserver/Build/Products/Release -filelist /Users/merethiel/websocketserver/Build/Intermediates.noindex/Server.build/Release/Server.build/Objects-normal/x86_64/Server.LinkFileList -mmacosx-version-min=10.13 -Xlinker -object_path_lto -Xlinker /Users/merethiel/websocketserver/Build/Intermediates.noindex/Server.build/Release/Server.build/Objects-normal/x86_64/Server_lto.o -stdlib=libc++ -lboost_system -Xlinker -dependency_info -Xlinker /Users/merethiel/websocketserver/Build/Intermediates.noindex/Server.build/Release/Server.build/Objects-normal/x86_64/Server_dependency_info.dat -o /Users/merethiel/websocketserver/Build/Products/Release/Server
ld: library not found for -lboost_system
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there a fix for this?

**Comment by Merethiel** [comment]
I have linked the static versions of boost_system and boost_chrono but XCode gives the ld error. I'll see if I can find an option to force xcode to use the static version. But I do have other sources that rely on boost which don't give this error. So I was wondering if it had something to do with the source code itself.

**Comment by zaphoyd** [comment]
WebSocket++ should work fine with both static and dynamic linking. As it is header only, the library doesn’t have any preference or any control of that layer of the build system.

I have run into the exact same problem you are experiencing both with WebSocket++ and other unrelated software that uses Boost on Xcode. Getting Xcode to prefer static linking can be a pain sometimes.

**Comment by Merethiel** [comment]
Ah! I managed to get it to work. It turns out, dragging the static libraries into the XCode project and checking the box "Copy files if needed" is what made the difference. I was able to compile the project using the static versions of boost. Thank you so much for the help!
