### ISSUE TITLE
boost async timer with bind

### ISSUE THREAD

**Issue by JadeVand** [zaphoyd/websocketpp#739]
Prior to using websocketpp I have a function that would create a timer for a callback event every 60 seconds. And the timer worked fine. But after including websocketpp into my project, it no longer compiles with the call to the timer. Calling bind in other areas of my code seems to work like for on_message and on_open events but not with boost's timer.
Here's the function call.

```cpp
ClientInstanceContext->GetTimer().expires_from_now(boost::posix_time::seconds(TIME_IN_SECONDS));
ClientInstanceContext->GetTimer().async_wait(bind(&ServerInstance::TimerEventCallback, this, ClientInstanceContext,boost::asio::placeholders::error));
```

Then the prototype to my callback looks like this.
```cpp
void ServerInstance::TimerEventCallback(ClientInstacePtr ClientInstanceContext, const boost::system::error_code& Error)
```
When I try to compile I receive the error "No matching function call to bind". I retrieved the asio object by calling InstanceRef->get_io_context().

But in other areas of my code, calling bind works fine.
Like this.
```cpp
InstanceRef->get_con_from_hdl(hdl)->set_ping_handler(bind(&ServerInstance::on_ping_with_context, this, InstanceRef,Arrived, ::_1, ::_2));
```

**Comment by zaphoyd** [comment]
The first thing I would try is fully qualifying `bind`, i.e. `boost::bind` vs `std::bind`. Depending on your compiler, C++ version, etc WebSocket++ may use the boost or the std version of the functional header. You'll want to match whichever version the library is using when using the `io_context` that the library generates.

**Comment by JadeVand** [comment]
I did try running it with boost::bind and std::bind but I get this strange error.
```  template <typename WaitHandler>
  BOOST_ASIO_INITFN_RESULT_TYPE(WaitHandler,
      void (boost::system::error_code))
  async_wait(BOOST_ASIO_MOVE_ARG(WaitHandler) handler)
  {
    // If you get an error on the following line it means that your handler does
    // not meet the documented type requirements for a WaitHandler.
    BOOST_ASIO_WAIT_HANDLER_CHECK(WaitHandler, handler) type_check;
```
From what I can tell the handler is accurate, as defined here.
https://www.boost.org/doc/libs/1_54_0/doc/html/boost_asio/reference/basic_deadline_timer/async_wait.html
And websocketpp and my code should rely on the same boost versions.
