### ISSUE TITLE
[Question] Is boost a must to use this lib?

### ISSUE THREAD

**Issue by nezen** [zaphoyd/websocketpp#741]
Is boost a must to use this lib?

**Comment by nezen** [comment]
I want to use this lib as my websocket client

**Comment by zaphoyd** [comment]
If you have a C++11 standard library available, then Boost is not required. See the FAQ at https://docs.websocketpp.org/faq.html, specifically the questions about how to use the library without Boost for more information.

**Comment by nezen** [comment]
Hi @zaphoyd , I read about the faq, but still I didn't find a way to compile websocketpp without boost(I just run cmake . && make), would you please tell me more about the details ? Thanks

**Comment by zaphoyd** [comment]
WebSocket++ is a header only library. There is nothing to compile.

If you mean, can you run the bundled make or scons files that build all of the unit tests and examples without boost then the answer is no, as the test suite uses the boost testing system.

You do not need to run the test suite or any of the bundled cmake files to use the library.

**Comment by xXTurnerLP** [comment]
The FAQ is not helpful at all _"For these situations there are additional defines available to fine tune which C++11 libraries and features are used. **TODO: more details about them.**"_

Someone forgot to do this TODO
