### ISSUE TITLE
Use of get_con_from_hdl from outside the handler loop

### ISSUE THREAD

**Issue by mstaz** [zaphoyd/websocketpp#756]
The note at get_con_from_hdl() tells that it should not be used outside the handler loop. But other endpoint functions which can be used from other places (if I'm not mixing up things), like send(), call it implicitly as well. In the end get_con_from_hdl() seems only to lock the weak_ptr. So would it be safe to call get_con_from_hdl() or directly lock the connection_hdl while performing short operations, like sending, from outside the handler loop?

**Comment by zaphoyd** [comment]
get_con_from_hdl() itself is safe to use outside of the handler loop. The resulting connection object is not necessarily safe though. All safe usages of the connection itself are wrapped behind endpoint methods that perform the weak pointer locking for you.

As a result a safe rule of thumb is that if you only use get_con_from_hdl()/upgrade the weak pointer from inside handlers and outside handlers exclusively use the endpoint wrappers you are guaranteed thread safety.

There may be other combinations that result in a thread safe program, but sticking to the above rule will ensure best compatibility with future updates and eliminate a lot of guesswork.

If there are things you want to access outside of the handler loop that don’t have endpoint wrappers already I would be curious what those items are.

**Comment by mstaz** [comment]
Thanks for the quick response and the explanation.
I'm thinking about using the connection in a wrapper separately or let's say more independent from the endpoint. Means e.g. calling connection->send(..) instead of endpoint->send(connection, ...). From what I can see, the library would allow that, but with the circumstance that handle needs to be locked from there.

**Comment by zaphoyd** [comment]
If you are careful yes, you can do that. I'd recommend sticking to functionality that does already have endpoint wrappers.

**Comment by mstaz** [comment]
Ok, this makes sense to me. Thanks for your help.
