### ISSUE TITLE
[Question] Send a message once a socket is running

### ISSUE THREAD

**Issue by Pimmmo** [zaphoyd/websocketpp#757]
Hi,

I used the basic client example to connect to a websocket (https://gist.github.com/zaphoyd/6021634) which works perfect and I am able to send a message with the on_open or on_message functions, but I can't seem to be able to send a message to a running socket.

Is there a way to do this?

I tried using the .send function the connection, but I can't seem to get the connection _hdl from the connection and I am not sure why this is necesary as I want to send the message with the connected client.

Could anyone please give me a clarification?

Thanks in advance!

**Comment by zaphoyd** [comment]
You can send messages outside of a handler (even from another thread) by storing the `connection_hdl` when the connection opens and calling `endpoint::send` using that handle later. The handle is used to identify which connection to send to as your endpoint might have multiple outstanding connections.
