### ISSUE TITLE
openssl version

### ISSUE THREAD

**Issue by walle-z** [zaphoyd/websocketpp#759]
@zaphoyd 
Hi man,can you tell me the openssl version?Because I used the openssl 1.1.0,it did not work.

**Comment by zhangguangfengz** [comment]
I'm on ubuntu 16.04

**Comment by Eggache666** [comment]
It works on Windows, openssl-1.1.1

**Comment by zhangguangfengz** [comment]
@Eggache666 ,thank you.I will try it.

**Comment by walle-z** [comment]
I find the ubuntu openssl should be  openssl-1.0.2
