### ISSUE TITLE
init_asio called from the wrong state Issue

### ISSUE THREAD

**Issue by tastydev** [zaphoyd/websocketpp#786]
Hello, i get the following error while restarting a previously used server.
I am using 
echo_server.stop_listening();
echo_server.stop();
echo_server.reset();
in the close function of my class to "clear" the server.
But if i start it again i get this asio error and can´t find any solution for it.
Do someone know what im doing wrong? 

Error after echo_server.init_asio() is called again:
[2019-01-03 08:38:01] [library] asio::init_asio called from the wrong state
invalid state

**Comment by Hammer2017** [comment]
I had the same problem, how did you solve it in the end?
