### ISSUE TITLE
reconnect on close handle fail

### ISSUE THREAD

**Issue by SheSnake** [zaphoyd/websocketpp#787]
Hello, I try to reconnect to ws server(after ping time out) in on_close handle but fail.. 
I try many method, but all fail..
1. reconnect use the same client and conn.
```
on_close() {
   m_client->connect(m_conn);
   m_client->run();
}
```
the result is: 
```
[2019-01-08 20:10:17] [connect] Successful connection
but the the on_open handle and on_message handle never happen after connection
```
2. reconnect after reset the client and recreate conn:
```
   m_conn->terminate(ec); // after it, ec is 0
   m_client->reset();
   m_client->asio_init();
   m_client->set_on_tls_handler();
   m_conn = m_client->get_connection(uri, ec);
```
when i reconnect to server use the code above in close_handler, the asio::ssl::context throw a asio.ssl error, when create a new ```boost::asio::ssl::context```, and the on_tls_handle is:
```
context_ptr WsClient::on_tls_init() { 
    context_ptr ctx = std::make_shared<boost::asio::ssl::context>(boost::asio::ssl::context::sslv23); // this line error and throw asio.ssl error when reconnect
   try {
       ctx->set_options(boost::asio::ssl::context::default_workarounds |
              boost::asio::ssl::context::no_sslv2 |
              boost::asio::ssl::context::no_sslv3 |
              boost::asio::ssl::context::single_dh_use);
   } catch (execpt) {
      ...
  }
```

can anyone give a correct example to reconnect ws server??? thanks!!!

**Comment by hristoivanov** [comment]
Hi, maybe this can help.
https://github.com/zaphoyd/websocketpp/issues/754#issue-353706390
