### ISSUE TITLE
about send without input

### ISSUE THREAD

**Issue by xiaoyongcheng** [zaphoyd/websocketpp#798]
on the server side, any sending is triggered by client or web. Is there any way to make send not triggered? I've tried it incorrect to add thread lock after half processing.

**Comment by zaphoyd** [comment]
You can add a thread to send or you can use the timer/interrupt handlers to periodically push messages. The bundled `telemetry_server` example shows how to use the timers to make a server that periodically pushes messages without client input. The `telemetry_client` example shows a similar arrangement using a separate thread. While `telemetry_client` is written from a client perspective, the same principles can be applied to the server.

**Comment by xiaoyongcheng** [comment]
I was unaware of your reply to my message,thank's a lot, I will go see the study
