### ISSUE TITLE
Understanding how it works: Who calls the message handler?

### ISSUE THREAD

**Issue by ColaColin** [zaphoyd/websocketpp#806]
I want to understand in more detail how the process of receiving a message works, when using the boost asio transport layer.

At the end of this process my on_message handler is called within the io_service thread, but:

Where does this process start client side in the websocketpp code? The network pushes a new package into my machine via the network interface, how does websocketpp know that package exists? Does it poll for that somehow? Is there some underlying OS-system that puts a task into the io_service?

I don't really have a technical problem, everything works great, but this is a question I've come up with that I cannot fully answer. Something has to somehow tell the io_service to execute on_message, but there are no other threads in the system I am aware of that could do that and I've not managed to find anything in the websocketpp code.

**Comment by zaphoyd** [comment]
Websocket++, when using the asio transport layer, uses Asio's event based io_service / io_context for network I/O. When a connection is established WebSocket++ registers an asyncronous callback function with Asio asking to be called back when data is recieved on the connected socket. Asio in turn registers an asyncronous callback function with the operating system's network stack using whatever methods of non-blocking I/O the operating system supports.

Asio loops processing outstanding handlers, one of which is to non-blockingly poll the operating system for new network data, typically via epoll (Linux-y), kqueue (BSD-y), or IOCP (Windows-y). If new data is avaliable Asio calls WebSocket++ back, which decodes the WebSocket frame and registers a new handler for more data. When one of these reads reaches the end of message marker, WebSocket++ calls back the client application using the message handler.

All of this happens asyncronously via interleaved handlers in the io_service thread. This method breaks up the I/O operations for a WebSocket connection into smaller bits, no one handler taking significant time or blocking, and allows many connections to be serviced efficiently without the overhead of a thread based connection.

More reading if you want to dig deeper:
- https://en.wikipedia.org/wiki/Proactor_pattern
- https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/overview/core/async.html
