### ISSUE TITLE
pong timeout on server intiated ping

### ISSUE THREAD

**Issue by MGraefe** [zaphoyd/websocketpp#807]
I want my server to periodically check if the clients are still connected, so I send a ping to each client once per second. I also receive a pong from each client so the pong_handler works, however the pong_timeout_handler doesn't. It simply isn't called even if the client doesn't answer because I pulled the network plug for example. I use the asio config and left the timeout value at it's default.

When I look at the test it seems that the client is supposed to send the ping instead of the server. Is pong_timeout not supported for the other way around?

**Comment by danielab1** [comment]
I am experiencing exactly the same thing. how can I do to trigger the pong timeout handler?

**Comment by zaphoyd** [comment]
Ping, pong, and the pong timeout handler work the same way on clients and servers with WebSocket++. My testing indicates that the pong timeout handlers are working as intended. This is a case covered by the integration test suite.

Please note though, that what the pong timeout actually tests for is a more narrow condition than it might seem. A pong timeout tests for the situation where you can write to the socket, i.e. the TCP connection itself is working, but the application on the other end is no longer working through the steps of the websocket protocol.

In most cases of network disruption something else will notice that the TCP connection is broken first. Either the write on your outgoing ping will fail or the read on incoming messages will fail and you will get a close handler call instead. Situations where the remote client is reading and acking TCP data but not responding to it are more rare, and are what the pong timeout tests. You can simulate this sort of condition to test your server code by creating a websocket client that deliberately doesn't answer pings. You can do this with WebSocket++ by adding a ping handler to your client that returns false.
