### ISSUE TITLE
Cannot Send message to server per sec

### ISSUE THREAD

**Issue by alice-thorn** [zaphoyd/websocketpp#852]
I send message from c++ client running on Windows to a node.js server running on Windows every second, but the server receives 5 same messages at one time .How can I send the message to server after "send()" immediately? Can anyone tell me how do I make sure the messages from the Client are received on the Server side without any buffering.
Here are my client codes:
while (true)
	{
		DWORD dw = WaitForSingleObject(m_hWebsocketProcessEvent,1000);
                m_connection->send("heartbeat");
        }

**Comment by zaphoyd** [comment]
Setting the TCP_NODELAY socket option usually helps with this. Operating systems, by default, typically buffer small tcp writes. Some details for how to set socket options in WebSocket++: https://stackoverflow.com/questions/23023317/proper-set-socket-init-handler-syntax-or-modify-source-to-turn-on-tcp-nodelay-wi
