### ISSUE TITLE
where is the lib after we build this project?

### ISSUE THREAD

**Issue by happyLiMing** [zaphoyd/websocketpp#856]
something is amazing happened when I compiled this project successfully.
step 1: 
git clone the master branch.

step 2:
mkdir build && cd build

step 3:
cmake ..  

the result seems to be ok ,just like this.
![image](https://user-images.githubusercontent.com/7010986/72000320-00dd6980-327e-11ea-9b48-b7b78dfea009.png)

step 4：
make install
it seems to to be ok anyway, just like this.
![image](https://user-images.githubusercontent.com/7010986/72000397-31bd9e80-327e-11ea-8983-222ba5855d7e.png)

but I can not found the lib as it tell me in the location **"/Users/admin/Desktop/websocketpp-master/build/lib"**. there is no "lib" folder in the "build" folder. 

so where is it ? thanks for your help.

**Comment by xinthose** [comment]
I think this is a header only library in `/usr/local/include/websocketpp`.  You have to link with boost in your Makefile: `-lboost_system`

**Comment by zghong** [comment]
WebSocket++ is just a header only C++ library, so it needn't build and it has no libs. All sources are in "./websocketpp/", and you can just copy them into your project.

**Comment by zaphoyd** [comment]
Closing this as the question has been answered, thanks @xinthose & @zghong
