### ISSUE TITLE
How to enable CORS

### ISSUE THREAD

**Issue by xinthose** [zaphoyd/websocketpp#858]
Hello,
    I have followed the broadcast server example [here](https://github.com/zaphoyd/websocketpp/blob/master/examples/broadcast_server/broadcast_server.cpp) and it works, but when my client connects to the server (using [socket.io-client](https://github.com/socketio/socket.io-client)) I get a CORS error:
**server**
```
[2020-01-09 10:07:24] [error] Handshake ended with HTTP error: 426
[2020-01-09 10:07:24] [fail] WebSocket Connection [::ffff:10.0.0.119]:57608 v0 
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/79.0.3945.117 Safari/537.36" /socket.io/?EIO=3&transport=polling&t=M-B3tVA 426
websocketpp:28 Upgrade required
```
**client** (using Chrome)
```
Access to XMLHttpRequest at 
'http://10.0.0.112:8090/socket.io/?EIO=3&transport=polling&t=M-B5o2l' 
from origin 'http://localhost:4200' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

How do I enable CORS on the server?

This is my unsuccessful attempt:

```
m_server.set_validate_handler(
	websocketpp::lib::bind(
		&websocket::validate, this,
		::websocketpp::lib::placeholders::_1
	)
);
```
```
bool websocket::validate(websocketpp::connection_hdl hdl) 
{
	server::connection_ptr con = m_server.get_con_from_hdl(hdl);
	con->append_header("Access-Control-Allow-Origin", "*");	

	return true;
}
```
Validate never gets called.

**Comment by xinthose** [comment]
I got this library working instead: https://github.com/socketio/socket.io-client-cpp

**Comment by MKaraszewski** [comment]
Hello, your solution was almost good, however you need to set a different handler:

bool on_httpinit(server * s, websocketpp::connection_hdl hdl)
{
	server::connection_ptr con = s->get_con_from_hdl(hdl.lock());
	con->append_header("Access-Control-Allow-Origin", "*");
	return true;
}

echo_server.set_http_handler(bind(&on_httpinit, &echo_server, ::_1));

best regards
Maciek Karaszewski

**Comment by xinthose** [comment]
That worked for me!  Thank you.
