### ISSUE TITLE
Bidirectional streaming: Sending continuous audio (binary) stream chunks and receive text results from server 

### ISSUE THREAD

**Issue by tumusudheer** [zaphoyd/websocketpp#861]
Hi,

I've a use case to send a continuous audio stream to a web server using TLS (wss://) and receive corresponding text, in a bidirectional streaming manner. I have to repeatedly send audio to the server until no more audio data. While the audio is being sent, server will start sending responses (with partial results) after some interval(from the time it started receiving audio).

I'm a beginner and could not find any samples or examples to do the above tasks. It would be great if I can get some example or pseudo code to do the same.

Thank you

**Comment by zaphoyd** [comment]
This is definitely something you can use WebSocket++ to do.

The high level overview would be to break up your audio data into smaller binary chunks and send those chunks using the binary WebSocket message type. On the server accepting those messages and passing the data off to another thread for collection, processing, and return feedback. The processing thread would feed the audio data into whatever code or library is doing the audio to text processing and if said code produced any output text, this thread would write a text message back on the same WebSocket connection.

`broadcast_server` example demonstrates a server that pushes messages into a queue for processing and response by a worker thread. The https://github.com/zaphoyd/heat_diffusion program demonstrates a server that uses a worker thread to perform long running jobs that periodically push status updates back to the client.

The exact details of how to break up audio data into binary chunks, perform audio to text processing, etc are outside the scope of this issue queue.
