### ISSUE TITLE
New version that support Boost 1.70 and beyond

### ISSUE THREAD

**Issue by aholzinger** [zaphoyd/websocketpp#862]
Hi, what is the blocker in creating a new version that considers the issues with boost::asio since version 1.70?

I'm aware that the develop branch addressed this issue, but the situation is far from being perfect, especially if you use libraries/repos that include websocketpp like i.e. cpprestsdk.

Attached is a patch for master that works with boost >= 1.70, tested under Windows by compiling the cpprestsdk (VS2017 and boost 1.170, VS2019 and bost 1.71 and 1.72).

I know the patch is far from optimal, but it already would help all the cpprestsdk users that can't downgrade to boost 1.69.
[0001-Make-websocketpp-usable-with-boost-1.70-and-higher.-.zip](https://github.com/zaphoyd/websocketpp/files/4080581/0001-Make-websocketpp-usable-with-boost-1.70-and-higher.-.zip)

**Comment by SimonZgx** [comment]
It working okay for me! Thanks a lot!

**Comment by dxtkdxtk** [comment]
Thanks! It works

**Comment by barsnick** [comment]
Have you instead tried the two commits on the "develop" branch, which were committed/merged there in April 2019?:
zaphoyd/websocketpp@c769c9238ad62178f506038178714a1c35aa2769
zaphoyd/websocketpp@f810ca2e800e9b55be41c5911cf1d1185fcd516b
They are supposed to fix build with boost:::asio >= 1.70.

**Comment by aholzinger** [comment]
Yes, that's it. Thank you very much!!!

**Comment by zaphoyd** [comment]
The fix for this issue has been available on the `develop` branch for some time and has now been published in release 0.8.2
