### ISSUE TITLE
Facing this issue while compiling " error: conversion from 'int' to non-scalar type 'boost::shared_ptr<tcp_connection>' requested"

### ISSUE THREAD

**Issue by kjaisinghyadav** [zaphoyd/websocketpp#865]
This issue is occurring for this method 

typedef boost::shared_ptr<tcp_connection> pointer;
pointer get(const int& id) {
        boost::lock_guard < boost::recursive_mutex > lock(m_lock);

        map_type::iterator it = m_conns.find(id);
        if (it == m_conns.end()) {
            return NULL;    // because of this its occurring
        }
        return it->second;
    }

i tried many things but still facing. please tell me what should i return here in order to avoid this error.

Actually, i do not want to use CmakeList.txt.  i am compiling direct code  by using this 
"g++ /usr/lib/ccache/c++ -DBOOST_TEST_DYN_LINK -DNDEBUG -std=c++0x -std=c++0x -Wall -fpermissive -O2 -I/abc-org/xyz    -Wall -Wcast-align 1.cpp 2.cpp 3.cpp 4.cpp" fot this i am getting may undefined reference like 
 undefined reference to `boost::system::generic_category()'
undefined reference to `boost::system::system_category()'
undefined reference to `vtable for boost::detail::thread_data_base'
undefined reference to `boost::thread::joinable() const' ............and may more

**Comment by dennisjongebloed** [comment]
It seems like your include directory/files is wrong/missing. You should use vcpkg to install websocketpp and boost. Check this link: https://github.com/zaphoyd/websocketpp/issues/864

**Comment by kjaisinghyadav** [comment]
i am using linux environment in that its giving error like "vcpkg: command not found". My  included  directories are  like -I/usr/include/boost, -I/usr/include, -I/usr/include/openssl.

**Comment by dennisjongebloed** [comment]
I'm not sure on how to install vcpkg on Linux. However I think there is alot of resource out in the WWW.

**Comment by kjaisinghyadav** [comment]
Actually i don't want to use Cmake file here. i want to create my own make file so can you suggest me what all library and flags i need to include in my make file. like -lpthread, -lboost_system....etc

**Comment by kjaisinghyadav** [comment]
i didn't change anything in this file but still i am getting these kind of error in this file "uri.hpp".
uri.hpp(164): error: no instance of overloaded function "std::basic_string<_CharT, _Traits, _Alloc>::append [with _CharT=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]" matches the argument list

parsing.hpp(445): error: no instance of function template "boost::io::detail::parse_printf_directive" matches the argument list

regex_match.hpp(100): error: no instance of overloaded function "boost::regex_match" matches the argument list

please tell me if i am missing any library or any other things.

**Comment by kjaisinghyadav** [comment]
Thanks, this issue is resolved.
