### ISSUE TITLE
Hircallay of this Labrary

### ISSUE THREAD

**Issue by note8g2018** [zaphoyd/websocketpp#866]
Dear Sir,
Hi,
I am a beginner C++ programmer.
Is there any Hircallay of the classes of this Library to understand what is going on because I do not want to use low level approach  ?
In my project, I need to stream picture and video and also send json from server to client and from client to server? is any good tutorials to learn how to do it?

Best Regards,
Tom,

**Comment by zaphoyd** [comment]
Full class documentation and the (somewhat limited) tutorials that currently exist can be found at https://docs.websocketpp.org. There are also a large variety of bundled example code that you can inspect.
