### ISSUE TITLE
Query for Disconnect Method

### ISSUE THREAD

**Issue by kjaisinghyadav** [zaphoyd/websocketpp#870]
Is there any Disconnect method like Connect " boost::asio::connect(socket, iterator, error);" use for connecting server. If yes, than which method is that, and how i can call than method to Disconnect from server. 

If i use "m_endpoint.close(closehdl,CloseCode::NORMAL_CLOSURE,"normal closure");//normal closure" than i get this error when i run my binary 
"SSL_alert_desc_string_long::Error code detected is:bad record mac"
Please tell me what i am doign wrong.

**Comment by zaphoyd** [comment]
`endpoint::close` or `connection::close` are the correct methods to use to request a connection close. With regards to the SSL error, this is not an error I have come across, but others with this issue around the web suggest that "bad record mac" is related to either a bad or outdated TLS certificate or the interference of third party anti-malware set to scan encrypted connections.
