### ISSUE TITLE
websocketpp not return when network is disable

### ISSUE THREAD

**Issue by dq5070410** [zaphoyd/websocketpp#903]
I run websocketpp as a client, liks blew:

int close_code = websocketpp::close::status::normal;
websocketpp::lib::error_code ec;
g_ws_endpoint.close(hdl_, close_code, "", ec);
g_ws_endpoint.stop_perpetual();
g_threadws->join();

when the network is disabled, I disconnet the websocketpp and exit websocket client like above, but the g_threadws->join() not return until i enable network at linux machine.
at Windows machine ,this is not this issue. Others met the issue?

**Comment by xinthose** [comment]
Have tried calling `stop_listening` as well?  See this issue: https://github.com/zaphoyd/websocketpp/issues/803#issuecomment-478380963

**Comment by dq5070410** [comment]
add the line code
g_ws_endpoint.stop();
before join the thread.
solve this problem.
