### ISSUE TITLE
How do I set the level of logging?

### ISSUE THREAD

**Issue by xinthose** [zaphoyd/websocketpp#904]
I see log levels here: https://github.com/zaphoyd/websocketpp/blob/378437aecdcb1dfe62096ffd5d944bf1f640ccc3/websocketpp/logger/levels.hpp#L59, but how do I use them?

I see a function called `set_channels` here: https://github.com/zaphoyd/websocketpp/blob/378437aecdcb1dfe62096ffd5d944bf1f640ccc3/test/logger/basic.cpp#L49 which seems promising.  

I want to set the log level for the entire application of the server.

Thank you.

**Comment by zaphoyd** [comment]
The logging reference article talks a bit more about how to set and clear channels: https://docs.websocketpp.org/reference_8logging.html

**Comment by xinthose** [comment]
@zaphoyd Thank you sir.  I found related code in your `debug_server.cpp`: https://github.com/zaphoyd/websocketpp/blob/1b11fd301531e6df35a6107c1e8665b1e77a2d8e/examples/debug_server/debug_server.cpp#L143

**Comment by xinthose** [comment]
@zaphoyd honestly, I like your library better than [`boost/beast`](https://github.com/boostorg/beast/tree/develop/example/websocket/server) (yours is simpler/easier to use).  I came here from using [socket.io-client-cpp](https://github.com/socketio/socket.io-client-cpp.git).  It does not support boost versions greater than 1.69 and is not being maintained.  Socket-IO has seemed to go by the wayside after that browsers natively support websockets now.
