### ISSUE TITLE
Secure echo server external dependencies

### ISSUE THREAD

**Issue by kamocio** [zaphoyd/websocketpp#907]
I'm building VS2015, 32bit echo_server_tls. 

I got an error: 

include\asio\ssl\detail\openssl_types.hpp(23): fatal error C1083: Cannot open include file: 'openssl/conf.h': No such file or directory

Is my understanding correct that I have to build OpenSSL with its entire toolchain? Its a large project. Is there anything more "self-contained" as far as getting tls-based samples to build? something like "headers only", or "headers + libs"?

**Comment by zaphoyd** [comment]
You do not necessarily need to compile OpenSSL from scratch if your platform has precompiled header+binary library packages. I know on Linux you can install the OpenSSL dev packages (which ship with headers + precompiled libraries) and that works fine with WebSocket++. I have not personally used precompiled OpenSSL packages on Windows, but the OpenSSL wiki does seem to indicate that there are some avaliable (https://wiki.openssl.org/index.php/Binaries) that might be worth trying.
