### ISSUE TITLE
Compile without exceptions?

### ISSUE THREAD

**Issue by sourjon** [zaphoyd/websocketpp#908]
Hello,

I'm working on a system that requires the code to be exception free.  I've seen a prior post asking about this (https://github.com/zaphoyd/websocketpp/issues/438) but it didn't appear to be resolved.  Is there a way to turn off exceptions without heavily modifying the library directly?

Thanks!

**Comment by zaphoyd** [comment]
I took another look through at what it would take to have a completely exception free build and while not trivial it has gotten a lot easier than it used to be as I've slowly shifted new code to support it. I think I might be able to toss up an exception free draft in the next week or two. A real world test use case could be helpful for completing that use case as well.

**Comment by zaphoyd** [comment]
Going to close this as a duplicate in favor of #438. There have been some code updates towards this goal and some additional details over on that issue.

**Comment by sourjon** [comment]
Hi @zaphoyd!  Sorry I didn't reply sooner.  The real world case would be related to devices that require (or perform better with) no exceptions.  That's fine to close.  Excited to see the update!

**Comment by zaphoyd** [comment]
Hi @sourjon yes, sorry I wasn't clear, I am familiar with why one would want to disable exceptions, what would be useful is having someone who already had an environment or codebase that disabled exceptions to try the new code and report back whether it actually works. =) I can do some theoretical tests but it would be nice to have some real world integration testing to confirm.

**Comment by sourjon** [comment]
Hi @zaphoyd ,

Yep.  I have such a codebase available.  I can definitely let you know once the updates posted.
