### ISSUE TITLE
Chrome cannot trust the certificate of the WSS session.

### ISSUE THREAD

**Issue by realray808** [zaphoyd/websocketpp#913]
We first used a self-signed certificate on the WSS server.Then, use Chrome to connect to the URL `wss://host:port.`
We meet this error:
```
ws_client.html:9 WebSocket connection to 'wss://host:port/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
```

But, we can use `https://host:port.` to access the URL and make the browser trust the certificate. 
Then, the connection of `wss://host:port.` can be established. 
So, is there any method to skip the HTTPS access ?

**Comment by zaphoyd** [comment]
The only good solution here is to use a certificate signed by a CA that Chrome already trusts.

**Comment by gengfeipeng** [comment]
How to use self signed certificates for verification

**Comment by realray808** [comment]
您的邮件已经收到 谢谢

**Comment by gengfeipeng** [comment]
你怎么解决的呢不用自签名证书
