### ISSUE TITLE
400 Bad Connection

### ISSUE THREAD

**Issue by weiguang-zz** [zaphoyd/websocketpp#926]
When I receive a message from the client and send a message to the client in another thread, a bad connection error will be reported. 

My implementation logic is：
1 In the on-open callback, save the connection to the client object：
```
void on_open(server* s, websocketpp::connection_hdl hdl) {
    std::cout << "open handler" << std::endl;
    Client client = Client(s, hdl);
    ClientRegistry::registe(client);
}
```
2 In the on-message callback, Will initialize a proxy object, and send a request to another service through the proxy object, this service is returned asynchronously.
```
void on_message(server* s, websocketpp::connection_hdl hdl, message_ptr msg) {
    std::cout << "on_message called with hdl: " << hdl.lock().get()
              << " and message: " << msg->get_payload()
              << std::endl;

    Command command = Command(msg->get_payload());
    Client client = ClientRegistry::findClient(hdl);
    Proxy *proxy = ProxyFactory::getProxy(command);
    proxy->sendCommand(client, command);
}
```
3 When the back-end service returns data, it will call the sendResponse method of the client object. Because the client object holds the connection object, it will call the connection to return the data to the client.
```
struct Client {
    long id;
    websocketpp::server<websocketpp::config::asio> *server;
    websocketpp::connection_hdl connection;

public:
    Client(websocketpp::server<websocketpp::config::asio> *pServer, websocketpp::connection_hdl weakPtr) {
        this->id = 1;
        this->connection = weakPtr;
        this->server = pServer;
    }

    void sendResponse(std::string msg) {
        try {
            this->server->send(this->connection, msg, websocketpp::frame::opcode::text);
        } catch (websocketpp::exception const & e) {
            std::cout << "send response failed because: "
                      << "(" << e.what() << ")" << std::endl;
        }
    }
};
```
The problem is: Step 3 will report bad connection errors.
![image](https://user-images.githubusercontent.com/17842829/92064585-5697f080-edd0-11ea-9061-097250975649.png)

However, when I send data to the client in on_message, no error will be reported.

Thank you for you help!!

**Comment by zaphoyd** [comment]
Does this happen every time, or only occasionally?

Generally, bad connection means that the handle didn’t point to a valid connection, which does happen sometimes if the connection has been closed by the time a long running process completes.

If it happens every time and quickly then we should look at when/why the connection might be closing or going out of scope. Do you have a close handler set up that could log when the connection closes in relation to when the send attempt is made?

**Comment by weiguang-zz** [comment]
I find the reason.  It is my fault， when the backend service returns， I used the wrong client to send the response. 
thank you for your help @zaphoyd

**Comment by peipei1213** [comment]
I also get this bad connection, I don't know why, I want to realize a function of realtime visualization. What I have tried is like following:
sever.h
`typedef websocketpp::server<websocketpp::config::asio> server;

class ImageServer {
public:
    ImageServer();
    // void setImage(const cv::Mat& img) { img_ = img; }  // Setter method for img_
    void on_open(websocketpp::connection_hdl hdl);
    void send_image(const cv::Mat& img);
    void run();

private:
    server m_server;
   websocketpp::connection_hdl hdl_; 
   std::mutex mutex_;
};`

server.cpp 
`ImageServer::ImageServer()  {
    m_server.init_asio();
    m_server.set_open_handler(std::bind(&ImageServer::on_open, this, std::placeholders::_1));
}
void ImageServer::on_open(websocketpp::connection_hdl hdl) {
    std::lock_guard<std::mutex> lock(mutex_);
    hdl_ = hdl;
}

void ImageServer::send_image(const cv::Mat& img) {
    std::lock_guard<std::mutex> lock(mutex_);
    server::connection_ptr con = m_server.get_con_from_hdl(hdl_);

    // Check the connection state
    if (con->get_state() != websocketpp::session::state::open) {
        std::cout << "Connection is not open, cannot send image." << std::endl;
        return;
    }
    std::vector<uchar> buffer;
    cv::imencode(".png", img, buffer);
    con->send(buffer.data(), buffer.size(), websocketpp::frame::opcode::binary);
}

void ImageServer::run() {
    m_server.listen(19002);
    m_server.start_accept();
    m_server.run();
}`

call this class in mian.cpp

`crow::SimpleApp App;

    CROW_ROUTE(App, "/command/<string>")
    ([&](crow::request &req, crow::response &res, const std::string &command)
     {
         if (command == "start")
         {
    // server.start_sending();
    for (int imageIndex = 299; imageIndex < dim.nB; ++imageIndex)
    {
         if (command == "stop")
         {
             break; // 
         }
        CHECK(cudaMemcpy(bscan_host, RR_abs + imageIndex * imageSize, imageSize * sizeof(float), cudaMemcpyDeviceToHost));
        cudaDeviceSynchronize();

        cv::Mat Bscan(imgHeight, imgWidth, CV_32F, bscan_host);
    
        cv::normalize(Bscan, Bscan, 0, 255, cv::NORM_MINMAX);
        Bscan.convertTo(Bscan, CV_8UC1);
       

        cv::Mat Img_show;

        cv::Point2f center = cv::Point2f(ScreenWidth / 2, ScreenHeight / 2); // 极坐标在图像中的原点
        cv::warpPolar(Bscan, Img_show, cv::Size(ScreenWidth, ScreenHeight), center, 1 * center.x,
                      cv::INTER_LINEAR + cv::WARP_POLAR_LINEAR + cv::WARP_INVERSE_MAP);
 imageServer.send_image(Img_show);
        std::this_thread::sleep_for(std::chrono::milliseconds(10));

        cv::imshow("Img_show", Img_show);
        cv::waitKey(1);
    }

    server_thread.join();
     }
  });

    App.port(18081).multithreaded().run();`
    
    
    when the member function send_image() was called, the bad connection occurs, I don't know why, did because I use the mutithread in the code?
    
    @zaphoyd
