### ISSUE TITLE
tcp no_delay causes error, version 8.2

### ISSUE THREAD

**Issue by BudDavis** [zaphoyd/websocketpp#944]
Hello,

This report is related to the following version, which is "main"

            commit 1b11fd301531e6df35a6107c1e8665b1e77a2d8e

The example program, testee_server, aborts when ran:

[bdavis@budlinux testee_server]$ ./a.out
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  set_option: Bad file descriptor
Aborted (core dumped)
[bdavis@budlinux testee_server]$ 

Traced back to line 92, showed below:

 testee_server.cpp

 90 void on_socket_init(websocketpp::connection_hdl, boost::asio::ip::tcp::socket & s) {
 91     boost::asio::ip::tcp::no_delay option(true);
 92     s.set_option(option);
 93 }

Looking through the commits and other problem reports, it looks like this was fixed recently, but my experience shows it is not.
Glad to provide any additional information required.

Regards,
Bud Davis

**Comment by chentiannan** [comment]
I also encountered this problem

**Comment by BudDavis** [comment]
// http version of on_socket_init
    void on_socket_init(connection_hdl hdl, boost::asio::ip::tcp::socket & s)
    {
      boost::asio::ip::tcp::no_delay option(true);
      s.lowest_layer().set_option(option);
    }

    // https version of on_socket_init
    void on_tls_socket_init(connection_hdl hdl, boost::asio::ssl::stream<boost::asio::ip::tcp::socket> & s)
    {
      boost::asio::ip::tcp::no_delay option(true);
      s.lowest_layer().set_option(option);


this fixed my problem.
