### ISSUE TITLE
/usr/include/websocketpp/common/asio.hpp:46:14: fatal error: asio/version.hpp: No such file or directory

### ISSUE THREAD

**Issue by Jean-GM** [zaphoyd/websocketpp#951]
the mingw return this error how i can fix this

**Comment by duthienkt** [comment]
I try to install asio lib via command, problem was solved
```
apt-get install -y libasio-dev
```

**Comment by Jean-GM** [comment]
dont need more im start coding my bot in discord.py thanks in anyway

**Comment by lyjnew** [comment]
windwos ：
 step 1： install vcpkg  
 step 2：  vcpkg  install asio
