### ISSUE TITLE
Close connection without awaiting a closing tls handshake?

### ISSUE THREAD

**Issue by 0xffset** [zaphoyd/websocketpp#953]
Hey, is it possible to close a connection without awaiting a closing tls handshake? My client connects to a server that drops the connection immediately without sending a handshake which causes my client to exit like this: 
![image](https://user-images.githubusercontent.com/57747276/103692672-6b5fdd00-4f98-11eb-8248-4d6138bf2f7d.png)

**Comment by wensheng-zhang** [comment]
The same issue is found in my client. 
Did you used async_shutdown to close connection?  
// get_connection()->get_socket().async_shutdown

**Comment by wensheng-zhang** [comment]
@0xffset
I think your answer is below:
websocketpp/connection.hpp
line 780~799 
`    /// Close the connection
    /**
     * Initiates the close handshake process.
     *
     * If close returns successfully the connection will be in the closing
     * state and no additional messages may be sent. All messages sent prior
     * to calling close will be written out before the connection is closed.
     *
     * If no reason is specified none will be sent. If no code is specified
     * then no code will be sent.
     *
     * The handler's on_close callback will be called once the close handshake
     * is complete.
     *
     * Reasons will be automatically truncated to the maximum length (123 bytes)
     * if necessary.
     *
     * @param code The close code to send
     * @param reason The close reason to send
     */
    void close(close::status::value const code, std::string const & reason);

    /// exception free variant of close
    void close(close::status::value const code, std::string const & reason,
        lib::error_code & ec);`

**Comment by 0xffset** [comment]
I closed the connection using the above mentioned method with those results. 
I never resolved the issue but I will close the issue since i abondend the project some time ago
