### ISSUE TITLE
How to create different events?

### ISSUE THREAD

**Issue by orgg92** [zaphoyd/websocketpp#958]
Hi, forgive me if I have missed an issue or somewhere in the documentation but how do we create events between Node and C++?

So far I do have bi-directional communication but what if I want to send a message on connect but then perform different events.  I'm used to SocketIO/WS format on Node naming each event/route - from what I've worked out the placeholders on C++ act as a similar thing when you register a handler, but how do I sync these up from each end?

I thought maybe as a last resort I could send JSON with an event attribute that would be a switch case (inside Node) but that wouldn't really help transferring data back to the C++ client.

**Comment by zaphoyd** [comment]
WebSocket++ is an implementation of the WebSocket protocol, which does not define any semantics for the content of messages. Socket.io included an additional abstraction protocol on top that provided additional features. Unlike with socket.io, you are free to encode your application layer protocol however you like.

JSON in text messages and protocol buffers in binary messages are common and have good support libraries in both C++ and Node. You can also define your own wire protocol with whatever semantics your application needs. Disambiguating multiple types of application layer messages using a type field in those app data messages is an appropriate solution. You’ll need to switch on that type on both sides.

**Comment by orgg92** [comment]
Ah okay, thanks for the information @zaphoyd, that makes sense. I'm coming at this from a way higher level so just trying to get my head around it. The language is still new to me and while I understand the concepts and can create them on my own, unravelling projects and libraries I find to be a real headache

I had a look through the documentation and can't seem to find a reference to a type - would this happen to be the opcode in the send function?

On my Node side, it seems to be picking up the correct events (on connect/message) but haven't tested them separately to determine if it's just firing all the events off.

I'm just wondering if it would be easier to use some arbitrary binary data/codes that will distinguish the message immediately following the binary data - not sure whether this would be possible if sending streams of data or if one side becomes blocking and "misses" that particular stream being sent?

**Comment by zaphoyd** [comment]
The WebSocket Protocol does have a type field (called opcode), but it is exclusively used for internal control purposes and is not really avaliable for use by end user applications. WebSocket++ primarily exposes the opcode in the context of message sending and recieving to differentiate whether a message should be interpreted as UTF-8 text or binary data.

If your application needs to differentiate between different types of application layer messages you will need to provide the structure for that yourself (or match the format of whatever WebSocket subprotocol you are using). Whether you do that in text via JSON or via binary data codes depends entirely on your application needs. The usual reasons apply. Text is easy for humans to handle and has good generic library support but more verbose on the wire. Binary is compact and efficient but often requires more complicated processing libraries.

**Comment by orgg92** [comment]
In the end I figured out a nice way to get things working the way I need - thanks for the advice. I'll close this issue as solved :)
