### ISSUE TITLE
Does a local websocket server need ping/pong mechanism? [Question]

### ISSUE THREAD

**Issue by naiteon** [zaphoyd/websocketpp#961]
I'm running a local websocketpp server only to interface a local webpage in kiosk mode reading data from sensors through websocket messages. Websocketpp is the bridge between my sensors and the page itself. 
Once the computer boots it starts the websocket server and the browser. The js client connects to the localhost websocket server everytime the connection's readyState is not 1 or 2. 

My question is, do I still need to exchange periodically ping pong messages between the local client and local server? If so how is the proper way to do so? I've checked websocketpp has a native ping pong mechanism but it seemed to be icmp related.

Thank you!

**Comment by zaphoyd** [comment]
**Short answer:** Probably not

**Longer answer:** The WebSocket Protocol has a protocol level ping/pong feature that can be used by implementations to send traffic on the TCP connection and confirm that the remote end is still understanding the protocol without triggering semantically meaningful events (i.e. data messages) at the application layer.

WebSocket Protocol pings and pongs are not related to ICMP, but they do run as special control messages multiplexed with regular message data on the WebSocket TCP connection.

The extent to which a WebSocket implementation exposes ping/pong controls or activity varies. The standard browser APIs generally do not provide any visibility or control of ping behavior. WebSocket++ defaults to this behavior, but also allows applications to more directly observe and control pings if they wish.

I would not worry about pings unless you have specific problems. Common situations where I've seen pings be useful:
- Applications with intermittent traffic through intermediaries like proxies or NAT systems that will drop connections that have been idle past a certain timeout. In this case, regular pings can provide enough traffic to keep the middleware from dropping the connection
- Applications with unreliable network conditions that result in the other endpoint disappearing without closing the connection. In this case regular pings can discover a disconnect quickly and alert or free up resources.

In the case of a browser directly connecting on the loopback it seems unlikely that the sort of conditions would be present that would require the server to send pings. Your measured experience would be the best guide.

**Comment by naiteon** [comment]
Thank you so much for your response! It was very clarifying and helpful! I'm closing this issue, congratulations for your work. I've been using it without any problems so far!
