### ISSUE TITLE
where does the namespace lib come from?

### ISSUE THREAD

**Issue by merkey** [zaphoyd/websocketpp#963]
I saw a lot of namespace "lib" in code, where does it come from? does it come from boost? how it works?
eg. 
**lib**::asio::ip::tcp::endpoint()
**lib**::make_shared<...>
**lib**::asio::error::make_error_code(...)
...

**Comment by zaphoyd** [comment]
The namespace lib is used to abstract a number of standard and third party libraries such that they can be swapped at compile time without changing core code. Basically any library with multiple independent implementations is namespaced in websocketpp::lib and aliased to whatever real library of that name the build environment chooses. This is used primarily in two cases:

1. C++11/boost polyfills. For example, the library uses `lib::shared_ptr` and that is mapped to either `boost::shared_ptr` or `std::shared_ptr` based on whether the C++11 STL is available. This allows the library to use C++11 STL features while maintaining backwards compatibility with C++98. This was also important early in the life of the library when many compilers only implemented half of the C++11 STL. If you found yourself in that position you could pull in just the missing library from boost.
2. Asio/boost switching. `lib::asio` Performs a similar role, allowing the transparent swap between `boost::asio`, the standalone version of Asio from its developer, and a hypothetical future STL version of Asio. This allows boost users to use boost Asio and not have to worry about compatibility or extra dependency management but also allows C++11 users to use the standalone Asio and drop the boost libraries altogether.
3. Finally, it allows client programs (for example, the bundled examples) to easily match “whatever utility lib WebSocket++ is using” to retain the ability to swap out dependencies later (or even between environments).

**Comment by merkey** [comment]
**hello, thank you so much for answer my questions.**  
I guess the namespace switching is support via "using", i have checked the asio.hpp in this project.

namespace websocketpp
{
namespace lib
{
#ifdef ASIO_STANDALONE
namespace asio
{
    **using namespace** ::asio;
    ...
}
#else
namespace asio
{
    **using namespace** boost::asio;
    ...
}
#endif
}
}

so it can be use namespace **lib::asio::ip::tcp::**endpoint() in other code file.
