### ISSUE TITLE
Implementing a fast data server

### ISSUE THREAD

**Issue by sancelot** [zaphoyd/websocketpp#983]
I would need to setup a server that serves data as follow. 
it serves binary data array and should be fast.
many client may connect.

after connecting, the client sends a start message, and the server replies with data array length and then the whole data array.

There may be some examples similar to this application ?

**Comment by zaphoyd** [comment]
The echo server examples all demonstrate this pattern of a server that accepts client connections, waits for a message, then sends a response. You’d need to fill in the parts of the program that read the client message and generate the appropriate response.
