### ISSUE TITLE
Is websocketpp suitable for embedded devices?

### ISSUE THREAD

**Issue by ahmedwahdan** [zaphoyd/websocketpp#988]

**Comment by yash101** [comment]
Why not?

**Comment by zaphoyd** [comment]
While not its explicit design goal, WebSocket++ has a lengthy history of being used in embedded devices. C++ is popular for controlling embedded equipment and WebSockets are popular for building browser based interfaces to control or monitor that sort of equipment.

WebSocket++ has minimal and flexible dependencies and should compile on a wide variety of hardware including ARM / 32 bit cpus, etc that are more common in the embedded world. If you have specific trouble using WebSocket++ on an embedded platform it would be worth opening an issue with more details.
