### ISSUE TITLE
How to start server again after calling stop_listening

### ISSUE THREAD

**Issue by checkraisefold** [zaphoyd/websocketpp#993]
I'm experiencing an issue in my project (https://github.com/checkraisefold/ROBLOXLink-Plugin/blob/upgrade-from-legacy/ROBLOXLink/dllmain.cpp) where the server will initialize, work, shut down, re-initialize, and not work. No exceptions seem to be thrown and I can't find the issue. I suspect I'm missing a function call to re-start the server.

**Comment by zaphoyd** [comment]
From WebSocket++'s perspective, the opposite of `stop_listening` is `listen` and `listen` can be called after `stop_listening` with no further setup.

If you are using the Asio transport though (which your example code indicates) you need to also consider the `io_service`/`io_context` run loop. Full documentation about managing the Asio run loop can be found in Asio's documentation. WebSocket++'s Asio transport just wraps the run loop from Asio proper.

Generally, if an Asio `io_service`/`io_context` runs out of work and ends (which will be the case if, as in your example, you stop listening and wait for all connections to end) you will not be able to call `run` again until you have reset using the `reset` or `restart` method. Which one to use depends on the version of Asio you are using.

WebSocket++'s Asio transport wraps the `reset` method as `endpoint::reset()`. You can also use `endpoint::get_io_service()` to retrieve a reference directly to the service that you can call reset/restart on.

More details at: https://think-async.com/Asio/asio-1.12.2/doc/asio/reference/io_context/reset.html

**Comment by checkraisefold** [comment]
Thank you so, so much @zaphoyd! I've made some changes in my code that finally fixes the issue I've been having for about a week.

**Comment by checkraisefold** [comment]
> From WebSocket++'s perspective, the opposite of `stop_listening` is `listen` and `listen` can be called after `stop_listening` with no further setup.
> ...

Additionally, this part is wrong. You _do_ need to call another function, which is start_accept to start the accept loop again.
