### ISSUE TITLE
Proper way to store connections?

### ISSUE THREAD

**Issue by checkraisefold** [zaphoyd/websocketpp#997]
Currently, my project uses an std::set with owner_less comparison to store connection_hdl's. This seems a bit over the top, and I can't find a proper example on how to store connections. Is this a good way to do it or is there a cleaner way?

Relevant line:
https://github.com/checkraisefold/ROBLOXLink-Plugin/blob/upgrade-from-legacy/ROBLOXLink/dllmain.cpp#L41

This is pretty non-critical since this solution works perfectly, but I intend to make more projects that use WebSocket++ and would want something easier to read.

**Comment by checkraisefold** [comment]
Apparently the other examples I've found use this exact same configuration. Closing this issue then.

**Comment by zaphoyd** [comment]
Using the `connection_hdl` as a key in associative containers (set, map, etc) makes sense. Doing so will require being more explicit about the comparator being used as you’ve noted. Typedefs can be used to make this a bit less verbose.

There are also situations where I will assign my connections integer or UUIDs instead and use those as container keys or store connection info in vectors and use the vector index as the “connection id”. For the most part that depends on your local application and the access and allocation patterns you are going for.
